### ISSUE TITLE
Markdown for docs

### ISSUE THREAD

**Issue by janosh** [materialsproject/atomate2#102]
Wouldn't normally raise an issue about this but @utf said

> It’s still early days without much adoption, so plenty of scope for changing [...]

May I recommend using markdown instead of rST for docs? While I admit I'm biased, I believe there are good reasons to be. They include all the ones [listed here](https://predictablynoisy.com/posts/2020/2020-01-22-rst-thoughts) plus others:

- syntax is too confusing (by far the most important point)
- setext instead of ATX headers (very annoying to type)
- no nesting of inline markup
- syntax is more verbose than markdown
- development of rST seems all but frozen (maybe some would argue that's a good thing in a markup language but I disagree esp. with fundamental features like inline markup nesting still missing)

[Sphinx supports](https://www.sphinx-doc.org/en/master/usage/markdown.html) markdown with little extra setup so I think the cost of switching wouldn't be that high. [MyST](https://myst-parser.readthedocs.io/en/latest) which Sphinx relies on for md parsing supports directives and extensions so I don't think there'd be any downsides.

**Comment by janosh** [comment]
Another important point: docs are something where new users are most likely to start contributing. rST is not used at all outside Python documentation and even among Python devs, the vast majority are more familiar with md than rST. Switching to md docs, I think, would make it more likely to receive user additions and corrections to the docs.

**Comment by utf** [comment]
I agree that rst is uncommon and takes some getting used to. The last time I checked, markdown couldn't match the functionality of rST (which is a first class citizen with sphinx) but perhaps things have moved on since then.

I think the docs need improvement in other ways too:
- I'm not a fan of the multi-section documentation e.g., I have User Guide, API Reference, and Developer Guide at the top, each with their own different side bars. It's really never clear which section you're in. I think a single section documentation with a structured side bar could be better.
- The "codes" subsection could do with a lot of work.

**Comment by janosh** [comment]
This would be possible with [`sphinx-markdown-tables`](https://pypi.org/project/sphinx-markdown-tables) which appears to be quite widely used ([4.6k "used by" on GH](https://github.com/ryanfox/sphinx-markdown-tables)).

The convenient thing about markdown is you can always fallback on a few lines of HTML here and there to cover edge cases. HTML admittedly is not less verbose than rST but also much more widely used and understood.

**Comment by janosh** [comment]
Or, maybe even better, would be to keep that snippet of rST as is and wrap it in `eval_rst`

````md
```eval_rst
.. csv-table::
   :file: vasp-workflows.csv
   :widths: 40, 20, 40
   :header-rows: 1
```
````

as supported by [recommonmark](https://recommonmark.readthedocs.io/en/latest/auto_structify.html#embed-restructuredtext).

**Comment by utf** [comment]
Ah ```eval_rst``` seems useful as it implies that there should be feature parity! Thanks for the information.

**Comment by arosen93** [comment]
Throwing my $0.02 in. I'm also very pro-markdown. The highest priority in my opinion should be to diminish the time it takes for a contributor to modify/add to the docs, and the best way to make sure they're already familiar with the syntax (oftentimes that means markdown).

**Comment by utf** [comment]
Just to let you know, I've started looking at this in #105

**Comment by janosh** [comment]
@utf Nice! Just to make you aware there's something wrong with the VASP wf table. Looked at the CSV and all seems correct but last line renders badly:

![Screen Shot 2022-03-31 at 09 30 00](https://user-images.githubusercontent.com/30958850/161053521-4806080f-f226-425f-b9bb-f63d1fbc5ac7.png)

**Comment by utf** [comment]
The markdown docs are complete. 

I also updated the [contributors page](https://materialsproject.github.io/atomate2/user/contributors.html) and revamped the [changelog](https://materialsproject.github.io/atomate2/user/changelog.html) with working links to the PRs.

Hopefully this will encourage others to add to the docs.
