### ISSUE TITLE
Use `pytest` `tmp_path` fixture

### ISSUE THREAD

**Issue by janosh** [materialsproject/atomate2#103]
Boy am I glad to see you're using `pytest`. 😄 

I noticed you wrote your own `tmp_dir` fixture.

https://github.com/materialsproject/atomate2/blob/614ace0ee657759091b6e39296614b07b42140c8/tests/conftest.py#L46-L58

`pytest` ships with a bunch of builtin fixtures including [`tmp_path`](https://docs.pytest.org/en/6.2.x/reference.html#std-fixture-tmp_path) which gives a `pathlib.Path` (and [`tmpdir`](https://docs.pytest.org/en/6.2.x/reference.html#pytest.tmpdir.tmpdir) which gives a `py.path.local` though that's scheduled for deprecation).

Happy to submit a PR to use the builtin (unless I'm missing some special requirement).

**Comment by utf** [comment]
I didn't realise that `tmp_path` existed. If you want to update the usage that would be great :)
