### ISSUE TITLE
Documentation Inconsistency in ElasticMaker Input Set Modification Example.

### ISSUE THREAD

**Issue by hongyi-zhao** [materialsproject/atomate2#1043]
As an example, I've dug into [ElasticMaker](https://materialsproject.github.io/atomate2/reference/atomate2.aims.flows.elastic.ElasticMaker.html#atomate2.aims.flows.elastic.ElasticMaker) for several days to understand it deeply. Based on my current understanding, it seems that the code setting snippet given [here](https://materialsproject.github.io/atomate2/user/codes/vasp.html#modifying-input-sets) is invalid:

> ```python
> # only update VASP jobs which have "deformation" in the job name.
> new_flow = update_user_incar_settings(
>     elastic_flow, {"ENCUT": 200}, name_filter="deformation"
> )
> ```

In [ElasticMaker](https://materialsproject.github.io/atomate2/reference/atomate2.aims.flows.elastic.ElasticMaker.html#atomate2.aims.flows.elastic.ElasticMaker), the two places for revising the input set are the `bulk_relax_maker` and `elastic_relax_maker`, by default, the former including two tight relax jobs, aka, `tight relax 1` and `tight relax 2`, the latter will dynamically create `N` VASP static computation jobs named from `elastic relax 1` to `elastic relax N` during the running process, where `N <= 24`, as noted [here](https://docs.materialsproject.org/methodology/materials-methodology/elasticity#formalism).

To summarize, some jobs in a flow are not real computations and there is no need to revise/update input set settings for them. If I'm wrong, feel free to correct me.

BTW, I go to [ElasticMaker](https://materialsproject.github.io/atomate2/reference/atomate2.aims.flows.elastic.ElasticMaker.html#atomate2.aims.flows.elastic.ElasticMaker) from the `ElasticMaker` listed [here](https://materialsproject.github.io/atomate2/user/codes/vasp.html#vasp-workflows). From the results below, there are several `ElasticMaker` classes defined in atomate2, and in this case, it should be pointed to the first one shown below:

```shell
$ ug 'class[ ]+ElasticMaker' -g '*.py'
src/atomate2/vasp/flows/elastic.py:class ElasticMaker(BaseElasticMaker):
src/atomate2/forcefields/flows/elastic.py:class ElasticMaker(BaseElasticMaker):
src/atomate2/aims/flows/elastic.py:class ElasticMaker(BaseElasticMaker):
```

See https://github.com/Neraaz/HTESP/issues/1#issuecomment-2451363600 for the related discussion.

**Comment by JaGeo** [comment]
@hongyi-zhao I don't fully understand the issues. 

Could you please produce a minimal example and tell us what is going different to what you are expecting. Thanks a lot.

**Comment by esoteric-ephemera** [comment]
@hongyi-zhao the documentation snippet for only updating jobs with `deformation` in the name just gives examples on how to update INCAR fields in jobs. It's not meant as practical advice.

You can see in the [source code for `update_user_incar_settings`](https://github.com/materialsproject/atomate2/blob/121936b41c60f138de9ae39232319d900c6d0887/src/atomate2/vasp/powerups.py#L64) that a class filter is applied to restrict INCAR updates to VASP jobs. A utility / glue job that dynamically spawns VASP jobs will not be updated, but its dynamically-created VASP jobs could be

@JaGeo :  the docs link to the wrong functions. The makers/flows in the VASP section of the docs link to FHI-AIMS

**Comment by JaGeo** [comment]
PRs are welcome to the docs as well

**Comment by hongyi-zhao** [comment]
> @hongyi-zhao the documentation snippet for only updating jobs with `deformation` in the name just gives examples on how to update INCAR fields in jobs. It's not meant as practical advice.

But it's very misleading, at least from my point of view when I try to learn it.

**Comment by hongyi-zhao** [comment]
@JaGeo 
> @hongyi-zhao I don't fully understand the issues.
> 
> Could you please produce a minimal example and tell us what is going different to what you are expecting. Thanks a lot.

It seems hard for me to produce a minimal example, but the above comment by @esoteric-ephemera also clarified the core idea that I want to express here.
