### ISSUE TITLE
Run some jobs of a flow in parallel through `run_locally`.

### ISSUE THREAD

**Issue by hongyi-zhao** [materialsproject/atomate2#1048]
Can I run some jobs of a flow in parallel through `run_locally`, say, for the static jobs created by ElasticMaker?

**Comment by JaGeo** [comment]
For parallel calculations, I would recommend having a look at [jobflow-remote](https://github.com/Matgenix/jobflow-remote)

**Comment by hongyi-zhao** [comment]
Only the independent jobs in a flow can be parallelized. Can [jobflow-remote](https://github.com/Matgenix/jobflow-remote) identify and tackle this automatically?

**Comment by JaGeo** [comment]
Yes. This is all done automatically.

**Comment by hongyi-zhao** [comment]
Thank you very much for letting me know about this wonderful tool and I'll give it a try.

**Comment by hongyi-zhao** [comment]
Can the flow created by atomate2 directly be fed to [jobflow-remote](https://github.com/Matgenix/jobflow-remote) to run?

**Comment by JaGeo** [comment]
Yes.

**Comment by hongyi-zhao** [comment]
The reason I raised the above question is that I couldn't find any introduction of compatibility with atomate2 in the source code and documentation of [jobflow-remote](https://github.com/Matgenix/jobflow-remote).

**Comment by JaGeo** [comment]
We are using it for running atomate2 workflows.
Jobflow-remote can deal with any jobfloww-based workflows. It think it is also mentioned in the atomate2 documentation that it can be used.

**Comment by hongyi-zhao** [comment]
Yes. The following gives some insightful explanations of the feature of the flow created by atomate2: https://materialsproject.github.io/atomate2/user/atomate-1-vs-2.html
