### ISSUE TITLE
Idea for job composition showcase: HSE@GGA 

### ISSUE THREAD

**Issue by janosh** [materialsproject/atomate2#107]
Not sure if this is a good idea, just a suggestion.

`atomate2` (or rather `jobflow`) is built to have [composable jobs](https://materialsproject.github.io/atomate2/user/index.html?highlight=compose#workflows). Would it make a good example for the docs to show off how this can be used to get a more precise band gap by using a GGA job to find the VBM and CBM k-points followed by an HSE job to get their precise energy levels? I.e. what is referred to [in the literature](https://www.nature.com/articles/am201557#Sec7) as HSE@GGA?

**Comment by jmmshn** [comment]
I have an example of something like this for defect calculations:
1. Create a supercell with the defect and do PBE calculation first
2. Hand the structure and WAVECAR off to start the HSE relaxation.
3. Finish the relaxation in HSE.

This should probably be the standard RelaxMaker for Defect HSE calculations or be included in the docs.
I will record this after PR #133

**Comment by janosh** [comment]
@jmmshn Weird, somehow I didn't get notified about your reply (or I missed it).

Thanks for the pointer! #133 is an impressive PR. 🚀
