### ISSUE TITLE
BUG: Potential Inconsistency in EOS Workflows

### ISSUE THREAD

**Issue by yanghan234** [materialsproject/atomate2#1071]
**Describe the bug**

When using the EOS workflows, I noticed the following code snippets. Based on the class names and their docstrings, I assume these classes are intended to generate input files compatible with MP GGA setups, specifically for PBE functionals. However, the `config_dict` defined within these classes references the `MPScanRelaxSet`.

Could you clarify whether this behavior is intentional (a feature) or an oversight (a bug)? Thank you for your help!

Here are the relevant code lines for reference:
https://github.com/materialsproject/atomate2/blob/4b84d781cc5beced4df81333aab063997e9b0a08/src/atomate2/vasp/sets/eos.py#L135-L138

https://github.com/materialsproject/atomate2/blob/4b84d781cc5beced4df81333aab063997e9b0a08/src/atomate2/vasp/sets/eos.py#L170-L173

**Comment by JaGeo** [comment]
@yanghan234 thank you for reporting this.

@esoteric-ephemera could you take a look? Thank you!

**Comment by esoteric-ephemera** [comment]
Hi @JaGeo and @yanghan234: the `MPGGA`-prefixed sets use slightly updated parameters for EOS workflows but are still PBE-based. Looking in the `incar_updates` property of each EOS, `METAGGA` is unset. The rationale was having parity between workflow parameters for PBE-GGA and r2SCAN-meta-GGA flows

The `MPLegacy`-prefixed flows use `MPRelaxSet` and a few settings specific to the atomate 1 EOS flows (for consistency/reproducibility)

The docstrings at the top of `vasp.jobs.eos` and `vasp.flows.eos` explain this, but I should probably move that to the docs for visibility

**Comment by JaGeo** [comment]
@esoteric-ephemera thank you! Yes, it would be great if this could be included in the Docs!

**Comment by esoteric-ephemera** [comment]
Sure thing, I'll add it to the doc PR I have up now

**Comment by yanghan234** [comment]
Thank you @esoteric-ephemera and @JaGeo! This resolved my concern.
