### ISSUE TITLE
BUG: ivdw not included in INCAR parameters

### ISSUE THREAD

**Issue by arosen93** [materialsproject/atomate2#113]
This is more a bug associated with the `vasprun.xml` format and, by extension a limitation of Pymatgen's `Vasprun('vasprun.xml).incar` object, but the IVDW flag is not included in the `input.incar` set of parameters below even if it's included in the INCAR.
https://github.com/materialsproject/atomate2/blob/7065ce387a4efefaaf96e12f7402e640ea0fee9a/src/atomate2/vasp/schemas/calculation.py#L167

This is because IVDW is not included in `vasprun.xml`, so there is a mismatch between the INCAR flags in `vasprun.xml` and IVDW.

Do you think it might be better to read in the INCAR flags from the INCAR itself, and if the INCAR isn't present, then pull it from the vasprun.xml? This would also be nice because there are a few extraneous flags included when the INCAR flags are pulled from the vasprun.xml (e.g. KPOINTS_BSE, LMAXTAU even if they aren't set in the INCAR).

**Comment by utf** [comment]
Yes, I'd definitely support this! 

I think its also a good idea to do the same thing in `VaspInputSetGenerator`, in particular here: https://github.com/materialsproject/atomate2/blob/7065ce387a4efefaaf96e12f7402e640ea0fee9a/src/atomate2/vasp/sets/base.py#L509

**Comment by arosen93** [comment]
Great! I can work on a PR for this in the near future 👍

**Comment by mkhorton** [comment]
@arosen93 have you submitted a bug report to VASP?

**Comment by arosen93** [comment]
I just posted a very brief comment on the forum.

**Comment by mkhorton** [comment]
Oh, I see it! Pasting a link here for future reference: https://www.vasp.at/forum/viewtopic.php?f=3&t=18465

**Comment by utf** [comment]
It's up to you. But I think enough people are using 5.4.1 that it could be useful still.

**Comment by arosen93** [comment]
Since it's resolved in VASP, I'm going to close the issue for now since I'm unfortunately a bit overloaded at the moment. If it's a problem for anyone else though, they'll know this is here!
