### ISSUE TITLE
Support for Lobster

### ISSUE THREAD

**Issue by JaGeo** [materialsproject/atomate2#160]
As atomate2 in combination with jobflows requires not much configuration, we would like to include Lobster support into atomate2 as well (similar to what we have done with atomate, https://chemistry-europe.onlinelibrary.wiley.com/doi/full/10.1002/cplu.202200123 )

If this is welcome, we (@naik-aakash and I) would start working on it.

**Comment by utf** [comment]
This is definitely welcome!

**Comment by JaGeo** [comment]
Great, thanks. I will start with the first draft once the phonon workflow is merged.

**Comment by utf** [comment]
Closed with #200
