### ISSUE TITLE
Clarify calcs_reversed in atomate2

### ISSUE THREAD

**Issue by Zhuoying** [materialsproject/atomate2#171]
Previously in the original atomate, `calcs_reversed` key is explicitly named for putting the final step as the first entry (https://github.com/hackingmaterials/atomate/blob/4577c94c1850fcebd8624d49ba1ab27f8e3e6d43/atomate/vasp/drones.py#L300)

In atomate2, the calculations are not in a reversed order, but still use this `calcs_reversed` key name, which may cause some confusions.
https://github.com/materialsproject/atomate2/blob/fe657b421a7d3b1a861da87f6d5994f3950c593f/src/atomate2/vasp/schemas/task.py#L382

To resolve this issue, we could:
(1) doing the calculation list in a reversed order, obey the principle of making the final step as first entry
 OR 
(2) keep the calcs in normal sequence (put initial step as the first entry), but rename it with a different key.

Please let me know which way you pro and I could submit a PR later.

**Comment by utf** [comment]
Hi @Zhuoying, thanks for bringing this to my attention. This should definitely be fixed. The best option is option 1 you suggested. If you could submit a PR that would be fantastic.

**Comment by utf** [comment]
Fixed in #182
