### ISSUE TITLE
LAMMPS Integration

### ISSUE THREAD

**Issue by JaGeo** [materialsproject/atomate2#173]
**Are there currently any plans on integrating LAMMPS?** 
I think there would also be many users. As there atomate workflows, I assume there might be plans.

**Comment by utf** [comment]
I'm not sure if anyone is working on LAMMPS at the moment, but this is definitely a feature I'm very interested in.

**Comment by JaGeo** [comment]
Maybe, we can talk about it next week and check if anyone has plans in this regard!

**Comment by mjwen** [comment]
+1 for LAMMPS integration. It seems the LAMMPS workflow in atomate1 is dead because of a lack of maintenance?

**Comment by davidwaroquiers** [comment]
@gbrunin is currently working on a Lammps in pymatgen for the inputs. He has some developments (based on earlier work by @manaslkjt and @rkingsbury) for which he will soon open an WIP PR in pymatgen (see https://github.com/gbrunin/pymatgen/tree/htmd/pymatgen).

**Comment by ml-evs** [comment]
After conversations with @gbrunin, @davidwaroquiers, @JaGeo, @gmrigna and others, I've started some work towards atomate2 LAMMPS integration over at [Matgenix/atomate2](https://github.com/Matgenix/atomate2) (see rough start in [Matgenix/atomate2#1](https://github.com/Matgenix/atomate2/pull/1/files)). 

This will involve the parallel development of a new pymatgen LAMMPS add-on package (see [Matgenix/pymatgen-io-lammps](https://github.com/Matgenix/pymatgen-io-lammps) and discussion at https://github.com/materialsproject/pymatgen/pull/2692 / https://github.com/materialsproject/pymatgen/issues/2754). Once we have a v0.1 of that package, I will make a PR here with a MWE, if that is still desired!

**Comment by ml-evs** [comment]
> This may involve the parallel development of a new pymatgen LAMMPS add-on package (see [Matgenix/pymatgen-io-lammps](https://github.com/Matgenix/pymatgen-io-lammps) and discussion at [materialsproject/pymatgen#2692](https://github.com/materialsproject/pymatgen/pull/2692) / [materialsproject/pymatgen#2754](https://github.com/materialsproject/pymatgen/issues/2754)). Once we have a v0.1 of that package, I will make a PR here with a MWE, if that is still desired!

I spoke to soon, looks like the IO stuff will just be updated in pymatgen directly; this makes things slightly more cumbersome for development here, as the LAMMPS part will need an as of yet unreleased pymatgen version, so happy to keep it as a separate atomate add-on if that is desired...

**Comment by JaGeo** [comment]
@ml-evs As I was just seeing this: I don't see an issue with just asking for a release of pymatgen as soon as the lammps interface is merged. 🙂 This should be fast.

**Comment by ml-evs** [comment]
Another dramatic twist in the tale... I think we are now planning on adding LAMMPS workflows as an atomate2 add-on (I believe there were offline discussions on this between @utf and @davidwaroquiers). I've started development in another new repo, https://github.com/matgenix/atomate2-lammps and will raise a separate issue about add-on packages shortly.

**Comment by utf** [comment]
I'm going to close this since https://github.com/matgenix/atomate2-lammps is now a thing. It looks like there haven't been many updates though, so if someone wanted to take that on (and potentially incorporate it into atomate2 main, then that could be an option).

**Comment by JaGeo** [comment]
With the increasing importance of ML potentials, LAMMPS is probably more interesting than ever
