### ISSUE TITLE
Suggestion: ALGO and LASPH in input sets

### ISSUE THREAD

**Issue by arosen93** [materialsproject/atomate2#18]
In `StaticSetGenerator` and `TightRelaxSetGenerator`, the ALGO flag is updated to "Normal". Unless there is a strong reason to keep it at "Normal", my personal suggestion would be to not specify ALGO as an update here. There are two reasons behind this suggestion:
1. Typically, static calculations are carried out in a flow following a relaxation job. If SCF convergence was difficult in the relaxation, Custodian may have updated ALGO one or more times (compared to what is in the `config_dict`) to land on something that works. Having the static calculation revert it back to "Normal" after this seems like it might be counterproductive.
2. If someone is using a meta-GGA, they almost always want to use ALGO = All. This may be in the `config_dict` or passed as a `user_incar_setting` earlier in the flow. Overwriting this to Normal may be problematic. Of course, using `user_incar_settings = {"ALGO": "All"}` in the `StaticSetGenerator()` would resolve this, but it's only obvious this is necessary after running the flow and seeing that ALGO was somewhat unexpectedly changed.

While I'm on this topic, I might suggest adding `"LASPH: True"` to all HSE generators in `vasp.sets.core`. This is already included in the default `config_dict`, but there is no guarantee that a user might remember to do this in a new `config_dict` even though VASP suggests using `LASPH = True` for hybrids. This is related to a warning I introduced in Pymatgen [here](https://github.com/materialsproject/pymatgen/pull/2297).

**Comment by utf** [comment]
Agreed on all points. This has been fixed in the `electron-phonon` branch.
