### ISSUE TITLE
BUG: Pre-commit results depend on dev environment's Python version

### ISSUE THREAD

**Issue by ml-evs** [materialsproject/atomate2#208]
**Describe the bug**
Without pinning a specific Python version using `default_language_version` in the pre-commit config, pre-commit will install hooks with the first available Python executable. This means that Python 3.10-specific code can get through the linting phase only to fail the 3.8/3.9 tests. This lso seems be the case in the CI, which installs pre-commit hooks from at Python 3.10 environment.

**To Reproduce**

- Create a Python 3.10 environment with your method of choice
- Clone and install atomate2 `pip install .\[dev\]`
- Introduce Python 3.10 specific code (e.g., replace a `typing.Tuple` with `tuple[str]`)
- `pre-commit install; pre-commit run --all-files` --- will pass without error.
- 
**Expected behavior**
Linters should use the minimum supported Python version (currently 3.8).

**Screenshots**

```diff
diff --git a/src/atomate2/settings.py b/src/atomate2/settings.py
index e87a1c0..4d2e0c5 100644
--- a/src/atomate2/settings.py
+++ b/src/atomate2/settings.py
@@ -7,6 +7,9 @@ from pydantic import BaseSettings, Field, root_validator

 _DEFAULT_CONFIG_FILE_PATH = "~/.atomate2.yaml"

+test: tuple[str, str] = ("a", "b")
+
+
 __all__ = ["Atomate2Settings"]
```

```shell
$ git commit -a -m "Attempt to introduce py10-only feature"
check yaml...........................................(no files to check)Skipped
fix python encoding pragma...............................................Passed
fix end of files.........................................................Passed
trim trailing whitespace.................................................Passed
autoflake................................................................Passed
black....................................................................Passed
blacken-docs.............................................................Passed
isort....................................................................Passed
flake8...................................................................Passed
type annotations not comments............................................Passed
rst ``code`` is two backticks........................(no files to check)Skipped
rst directives end with two colons...................(no files to check)Skipped
rst ``inline code`` next to normal text..............(no files to check)Skipped
mypy.....................................................................Passed
codespell................................................................Passed
pyupgrade................................................................Passed
[ml-evs/update_flake8_precommit b5e62c4] Attempt to introduce py10-only feature
 1 file changed, 3 insertions(+)
```

The simple fix is to use:

```
default_language_version:
   python: python3.8
```

at the top of the pre-commit config.

**Comment by utf** [comment]
Thanks for noticing this. It would be great if you could submit a PR!

**Comment by utf** [comment]
Actually, thinking about this. The only solution is to run the linting with multiple python versions.

**Comment by utf** [comment]
This is fixed in master.

**Comment by utf** [comment]
After more thought, I think it's sufficient to just run linting for the lowest supported python version.
