### ISSUE TITLE
dir_name name not necessary

### ISSUE THREAD

**Issue by fraricci** [materialsproject/atomate2#228]
https://github.com/materialsproject/atomate2/blob/38654604d813c3dae26bbf9cd6dd74374163d634/src/atomate2/vasp/schemas/calculation.py#L669

I think that the "*_file" contains already the full path and adding the dir_name is not necessary. It works because Path removes duplicates of following full paths, something like this:
`Path.cwd() / Path.cwd()`
where the output is just one single path (no duplicate).

But, using partial paths makes this failing because Path does not remove the duplicate here:
```
In [140]: Path("./outputs/") / Path("./outputs/")
Out[140]: PosixPath('outputs/outputs')
```

Therefore, removing the dir_name should also make this work providing a partial path.

Just for context, I was doing some tests creating a TaskDocument manually:
```
TaskDocument.from_directory(Path("./ferroelectric--23779/polarization_nonpolar/outputs/"))

FileNotFoundError: [Errno 2] No such file or directory: 'ferroelectric--23779/polarization_nonpolar/outputs/ferroelectric--23779/polarization_nonpolar/outputs/vasprun.xml.gz'
```
where you can see the duplicate path.

Please, double check this. It might be happening somewhere else too.

**Comment by utf** [comment]
This is a good catch, thank you! Would you mind adding a test to catch the bug and also submitting a fix?

**Comment by fraricci** [comment]
Sure! I'll submit a fix and a test soon.
I'll check if a similar use of Path is somewhere else as well.

**Comment by utf** [comment]
The task documents have been moved to emmet, so I'm closing this issue now.
