### ISSUE TITLE
Documentation (fireworks)

### ISSUE THREAD

**Issue by JaGeo** [materialsproject/atomate2#278]
I did not find any documentation on how to run jobs from atomate2 with multiple workers in fireworks. I assume this would be too hard to find out for a new user of atomate2 on their own.

**Comment by arosen93** [comment]
Hopefully we can add some clear documentation about this in the jobflow repo and then link to it in the Atomate2 docs. I opened an issue a while ago. It's still on my radar... https://github.com/materialsproject/jobflow/issues/90

**Comment by JaGeo** [comment]
This would be great! Especially for workflows where more than 1 code andmore than one worker are needed! Thanks!

**Comment by arosen93** [comment]
When you say more than one worker, could you clarify what you mean? Do you mean more than one HPC machine?

**Comment by JaGeo** [comment]
It's triggered by the Lobster workflow. VASP uses MPI parallelization. Lobster itself OpenMP. It would be great to have an example where we have one worker running, e.g., VASP jobs and the other one e.g. Lobster jobs with a different job script.

**Comment by arosen93** [comment]
Note to self:

- Tutorial on how to dispatch jobs in a workflow across multiple FW configs (eg different SLURM scripts and resources).
- For above, specifically need to highlight how this is done based on something like setting metadata in jobflow so the user can associate each job with a given Fireworks config.
