### ISSUE TITLE
Feature: Support for alternate KPath types

### ISSUE THREAD

**Issue by arosen93** [materialsproject/atomate2#29]
In the code block below, it seems that `HighSymmKpath` is called without any supplemental kwargs. It would be ideal if the user could modify the `HighSymmKpath` args on-the-fly, e.g. to get `path_type = 'latimer_munro'` instead of `path_type = 'setyawan_curtarolo'`. I assume this is not currently possible, right? If not, I've left this issue open as a possible feature to add in the future.

https://github.com/materialsproject/atomate2/blob/2eec3b6b0d8ff7d98e0b44de80ac9d9d2b8b130e/src/atomate2/vasp/sets/base.py#L664-L677

**Comment by utf** [comment]
I added generic support for any HighSymmKpath options by adding a `kpath_kwargs` option to the kpoints config dict. Note, this config dict really needs documentation before I forget all the specifics!

See: 623d56cac72cfa150b5a6e81eb11e46baf579069
