### ISSUE TITLE
Potentially increase efficiency of deformation calculations in elastic constant workflow

### ISSUE THREAD

**Issue by matthewkuner** [materialsproject/atomate2#290]
https://github.com/materialsproject/atomate2/blob/de92307b0d3b3bfcb5d66d3073372b7ef01775de/src/atomate2/vasp/flows/elastic.py#L113

When running the elastic constants workflow for metallic systems (HEAs primarily), I find that the calculations for many of the deformations is 1/3 - 2/3rds as expensive as the initial tight relaxation. This is especially true for the shear deformations. And with up to 24 of these calculations, that really adds up.

Perhaps it would be efficient to have each of the deformation calculations be ran in two stages:
1. an initial relaxation with a lower kpoints density and/or looser EDIFFG
2. a second relaxation with the current deformation calculation's kpoints/EDIFFG

Could someone with a deep(er) understanding of elastic constant calculations weigh in on this? For my systems, these deformation calculations make up >80% of the run time of my flows, so there is a ton of potential upside.

**Comment by mkhorton** [comment]
A check, but (1) are you symmetrizing your input structures before passing them to the workflow, and (2) have you tried running with fewer `strain_magnitudes` (e.g., `np.arange(0.01, 0.01 * 2, step=0.01)`) to see if you still get reasonable answers?

In terms of the correct answer here, I don't think anyone can tell you without running benchmarking yourself.

**Comment by matthewkuner** [comment]
1) no, but that is because I’m working with high entropy alloy cells that usually have triclinic symmetry + I expect symmetrically identical sites to likely experience different local distortions. Let me know if I’m misinterpreting what structure symmetrization does. 
2) I’ll have to look into using fewer deformation magnitudes

Perhaps I’ll do some benchmarking when I get the chance

**Comment by matthewkuner** [comment]
Did not mean to close, apologies
