### ISSUE TITLE
MAGMOM from INCAR does not work

### ISSUE THREAD

**Issue by xivh** [materialsproject/atomate2#298]
I set a MAGMOM in my INCAR and used pymatgen to read it as the input set. This makes a 'magmoms' list, but I think atomate2 wants it to be a dictionary:

```
my_structure = Structure.from_file('POSCAR')
my_incar = Incar.from_file('INCAR')
my_input_set = RelaxSetGenerator(user_incar_settings=my_incar.as_dict())
relax_job = RelaxMaker(input_set_generator=my_input_set).make(structure=my_structure)
```

Error:
```
File ".../atomate2/lib/python3.9/site-packages/atomate2/vasp/sets/base.py", line 857, in _get_magmoms
    mag.append(magmoms.get(site.specie.symbol, 0.6))
AttributeError: 'list' object has no attribute 'get'
```

https://github.com/materialsproject/atomate2/blob/4a9dc111b2d2f729f974067c67f550e0b2b5b9cc/src/atomate2/vasp/sets/base.py#L851

**Comment by arosen93** [comment]
I imagine the canonical way to do this is to fetch the magnetic moments from the INCAR object and attach them to the structure before running Atomate2. I don't think they are attached here. So, something like `my_structure.add_site_property("magmom", magmoms_list_from_incar)`. See https://pymatgen.org/pymatgen.core.structure.html#pymatgen.core.structure.SiteCollection.add_site_property

**Comment by xivh** [comment]
I see. Is there a way to completely override the default INCAR, i.e. only use my settings and turn off any tags that I did not set?

**Comment by utf** [comment]
Currently, there is no option to do this.
