### ISSUE TITLE
Feature: Support for different makers in the DoubleRelaxMaker

### ISSUE THREAD

**Issue by arosen93** [materialsproject/atomate2#30]
In the `DoubleRelaxMaker` flow, currently the same `relax_maker` is used for step 1 and step 2. It would be desirable to split this up into two makers (which by default are the same) in case the user wants to do something like a half k-point relaxation for step 1.

I can take care of this modification. This is mainly a reminder for myself.

**Comment by utf** [comment]
Closed with #32
