### ISSUE TITLE
Molecule schema should probably be merged within emmet

### ISSUE THREAD

**Issue by arosen93** [materialsproject/atomate2#300]
Currently, the `MoleculeMetadata` class is in Atomate2 [here](https://github.com/materialsproject/atomate2/blob/main/src/atomate2/common/schemas/molecule.py). Longer term, it probably makes sense to either port it to emmet where it can co-exist with [StructureMetadata](https://materialsproject.github.io/emmet/core/#emmet.core.structure.StructureMetadata) or, potentially better yet, adopt/merge with whatever @espottesmith is planning to do (or has already done) in terms of making a `MoleculeMetadata` for MP. For now, what we have works though.

**Comment by espottesmith** [comment]
There is a MoleculeMetadata class now in emmet main. Take a look and see if it fits your needs.

**Comment by arosen93** [comment]
Ah thanks! I must have missed it when looking before.
