### ISSUE TITLE
'overwrite' argument question/confusion

### ISSUE THREAD

**Issue by matthewkuner** [materialsproject/atomate2#308]
https://github.com/materialsproject/atomate2/blob/9c99ccd7b1e54b39dfddcc798a98d90f60e48475/src/atomate2/vasp/sets/base.py#L114

If the purpose of the 'overwrite' argument is to continue using input files that already exist, why does this line give an error if the input files already exist? Shouldn't it be the opposite? Or am I just confused...

**Comment by JaGeo** [comment]
If this question is still an issue, please reopen but I assume that 1 year was likely enough to ask again.
