### ISSUE TITLE
BUG: Incorrect elastic tensor of FCC Si due to bug in _expand_deformations

### ISSUE THREAD

**Issue by dengtq** [materialsproject/atomate2#333]
**Describe the bug**
The elastic tensor of FCC Si calculated using ElasticMaker is incorrect with `sym_reduce=True` (default). The `C_44` is only 1/3 of the correct value.
The bug originates from incorrect exclusion of some rotated deformation in `_expand_deformations` of `atomate2.common.schemas.elastic`. It could also affect other calculations with moderate symmetry.

**To Reproduce**
The behavior can be reproduced using the following simple example.
```
from atomate2.vasp.flows.elastic import ElasticMaker
from atomate2.vasp.powerups import update_user_incar_settings
from atomate2.vasp.powerups import update_user_kpoints_settings
from jobflow import run_locally
from pymatgen.core import Structure
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
import numpy as np

# construct an FCC silicon structure
si_structure = Structure(
    lattice=[[0, 2.73, 2.73], [2.73, 0, 2.73], [2.73, 2.73, 0]],
    species=["Si", "Si"],
    coords=[[0, 0, 0], [0.25, 0.25, 0.25]],
)
si_structure = SpacegroupAnalyzer(si_structure).get_conventional_standard_structure()

# job with different sym_reduce
for sym_reduce_bool, sym_reduce_str in zip([True,False],['true','false']):
    elastic_job = ElasticMaker(bulk_relax_maker=None,sym_reduce=sym_reduce_bool).make(si_structure)
    elastic_job = update_user_incar_settings(elastic_job, {"ENCUT": 200, "ENAUG": None}, name_filter="relax")
    elastic_job = update_user_kpoints_settings(elastic_job, {"grid_density": 100}, name_filter="relax")

    responses = run_locally(elastic_job, create_folders=True)
    elastic_output = responses[elastic_job.jobs[-1].uuid][1].output

    ieee_tensor = elastic_output.elastic_tensor.ieee_format
    raw_tensor = elastic_output.elastic_tensor.raw

    np.savetxt('sym_reduce_{}_ieee.txt'.format(sym_reduce_str),ieee_tensor, fmt='%10.4f')
    np.savetxt('sym_reduce_{}_raw.txt'.format(sym_reduce_str),raw_tensor, fmt='%10.4f')
```

**Expected behavior**
The symmetrized tensor should not be too far away from raw data, and `sym_reduce` should not significantly affect the results. But using `sym_reduce = True`, the raw tensor is
```
  152.3951    62.4105    62.4105   -39.0322     0.0000     0.0000
   62.4105   152.3951    62.4105   -39.3736     0.0000     0.0000
   62.4105    62.4105   152.3951   -39.3736     0.0000     0.0000
  -39.0322   -39.3736   -39.3736    76.1099     0.0000     0.0000
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000
    0.0000     0.0000     0.0000     0.0000     0.0000     0.0000
```
while the IEEE-standard-symmetrized tensor is 
```
  152.3951    62.4105    62.4105     0.0000     0.0000    -0.0000
   62.4105   152.3951    62.4105     0.0000     0.0000    -0.0000
   62.4105    62.4105   152.3951     0.0000     0.0000    -0.0000
    0.0000     0.0000     0.0000    25.3700    -0.0000     0.0000
    0.0000     0.0000     0.0000    -0.0000    25.3700     0.0000
   -0.0000    -0.0000    -0.0000     0.0000     0.0000    25.3700
```
They are very different and this `C_44=25.37` is very far from the the experimental value `76.9`.

With `sym_reduce=False`, they are very close
raw
```
  152.3951    62.4096    62.3477    -0.0000    -0.0000    -0.0000
   62.4096   152.3932    62.3468     0.0000     0.0000    -0.0000
   62.3477    62.3468   152.2648     0.0000    -0.0000     0.0000
   -0.0000     0.0000     0.0000    76.1504     0.0000    -0.0000
   -0.0000     0.0000    -0.0000     0.0000    76.1504    -0.0000
   -0.0000    -0.0000     0.0000    -0.0000    -0.0000    76.1503
```
IEEE
```
  152.3511    62.3680    62.3680     0.0000     0.0000    -0.0000
   62.3680   152.3511    62.3680     0.0000     0.0000    -0.0000
   62.3680    62.3680   152.3511     0.0000     0.0000    -0.0000
    0.0000     0.0000     0.0000    76.1504    -0.0000     0.0000
    0.0000     0.0000     0.0000    -0.0000    76.1504     0.0000
   -0.0000    -0.0000    -0.0000     0.0000     0.0000    76.1504
```
And this `C_44=76.15` is very close to experimental value `76.9`.

**Origin of BUG**
The following lines in `_expand_deformations` of `atomate2.common.schemas.elastic` incorrectly excluded some `rotated_deformation` that should be included,
```
            if not Deformation(rotated_deformation).is_independent():
                continue
```
For example in FCC Si, the pure shear strain `epsilon_xy` or `epsilon_6`
```
 0.000  0.005  0.000
 0.005  0.000  0.000
 0.000  0.000  0.000
```
can be realized by deformation matrix
```
 0.99995  0.00000  0.00000
 0.01000  1.00000  0.00000
 0.00000  0.00000  1.00000
```
But this deformation is excluded in `_expand_deformations` when rotated from the computed `epsilon_yz` or `epsilon_4`. This caused zero C_55 and C_66 in the raw data, and therefore incorrect final IEEE-standard tensor.

**Proposed Solution**
Instead of checking whether the Deformation is "independent", we should check whether the strain is independent and not seen before. So I added this method
```
def _strain_is_independent(deformation: Deformation, tol: float=1e-8):
    # get strain in Voigt form from deformation
    strain_voigt = deformation.green_lagrange_strain.voigt
    # check how many strain components are involved
    n_perturbed = (abs(strain_voigt) > tol).astype(int).sum()
    # the strain is independent only if there is exactly one non-zero Voigt component
    return n_perturbed == 1
```
to replace the above-mentioned lines. The `mapping` also should record `Strain` instead of `Deformation` because the same strain may be realized with different deformation.

Using the modified code, both raw and symmetrized tensors are correct:
Raw
```
  152.3951    62.4105    62.4105    -0.0000    -0.0000     0.0000
   62.4105   152.3951    62.4105    -0.0000    -0.0000     0.0000
   62.4105    62.4105   152.3951    -0.0000    -0.0000     0.0000
   -0.0000    -0.0000    -0.0000    76.1504     0.0000     0.0000
   -0.0000    -0.0000    -0.0000     0.0000    76.1504    -0.0000
    0.0000     0.0000     0.0000     0.0000    -0.0000    76.1504
```
IEEE
```
  152.3951    62.4105    62.4105     0.0000     0.0000    -0.0000
   62.4105   152.3951    62.4105     0.0000     0.0000    -0.0000
   62.4105    62.4105   152.3951     0.0000     0.0000    -0.0000
    0.0000     0.0000     0.0000    76.1504    -0.0000     0.0000
    0.0000     0.0000     0.0000    -0.0000    76.1504     0.0000
   -0.0000    -0.0000    -0.0000     0.0000     0.0000    76.1504
```

If the fix looks reasonable to you and is of interest, I can make a PR or attach the modified code. But it could break the test `tests/vasp/flows/test_elastic.py ` whose C_44 seems also incorrect.

Best Regards,
Tianqi Deng
MSE&HIC
Zhejiang University

**Comment by matthewkuner** [comment]
I am unsure about how to correctly fix the symmetry reduction, but I also noticed an issue while using `symmetry_reduce=True` in the past for other materials.

**Comment by mjwen** [comment]
I guess I've mentioned to @matthewkuner before that I've seen similar error in MP elasticity builder and will make a PR to atomate2. I believe this is a great time to solve this. 

@dengtq I already have a version using strain instead of deformation implemented in emmet: 
https://github.com/materialsproject/emmet/blob/24009ded28dd77f5a1d61c98cd6707481d17ed5f/emmet-core/emmet/core/elasticity.py#L325 In addition to what you've suggested, the emmet implementation also keeps all symmetry related stresses and averages them to obtain the stress for a deformed structure that does not have explicit VASP calculation. I've done this because stressed obtained from different explicit calculations can be different due to sym_prec and related numerical errors. Averaging might reduce the error.   

@utf weakly related: I saw you've combined the TaskDoc with the emmet one. Would be great if we combine the ElasticDoc and related stuff as well.

**Comment by dengtq** [comment]
Thank you for the clarification! This is much more sophisticated than my simple fix. Look forward to its implementation in atomate2.

**Comment by utf** [comment]
Hi @dengtq, thanks for raising this issue.

@mjwen your emmet PR looks great - I agree it would be good to merge atomate2/emmet task documents. Would you be interested in attempting this?
