### ISSUE TITLE
Not allowing workflows for elastically unstable structures to complete

### ISSUE THREAD

**Issue by matthewkuner** [materialsproject/atomate2#334]
https://github.com/materialsproject/atomate2/blob/b4a87a38a8b02a0b73284ce029acf9d97ea1b6a6/src/atomate2/common/schemas/elastic.py#L216

Hi all--

I've been attempting to run some elastic workflows on structures that I know will be elastically unstable. However, some of the DerivedProperties are obviously unphysical, causing the workflows to error. Would it be reasonable to introduce some sort of task_doc_kwarg to the elastic_flow to address this? Useful information can still come from elastically unstable structures.

**Comment by utf** [comment]
Hi Matthew, I think that would be very useful!
