### ISSUE TITLE
Port SCAN workflows to atomate2

### ISSUE THREAD

**Issue by janosh** [materialsproject/atomate2#352]
MP currently stands at 33k r2SCAN calculations out of 154k materials. Eventually, we'd like to have 100% r2SCAN coverage.

The [current workflows are implemented in `atomate1`](https://github.com/hackingmaterials/atomate/blob/387938da7c578481c41aa4cfeb65a166778e6372/atomate/vasp/workflows/presets/scan.py#L9-L48C14). This issue is to track porting them to `atomate2`.

@utf Would be great to hear your thoughts (if any). @arosen93 and I were thinking of hacking something together to open a draft PR and then iterate with your feedback.

**Comment by utf** [comment]
Yes, please port them over!

One issue is I removed auto_kspacing from the VASP input sets because I don't think tying the k-mesh to the band gap is a good idea. See https://github.com/materialsproject/atomate2/pull/270

To be faithful to the MP implementation, auto_kspacing would have to be added in again. Although I personally think it would be fine to use the default k-point logic already in atomate2.

**Comment by mkhorton** [comment]
I've been thinking about this too, thanks for initiating!

As a rough sketch, I was thinking:

- A `Job` with `MPScanRelaxSet` as the default
- A `Flow` with two jobs (1) a pre-relax, and (2) the SCAN relax, where (1) passes along an output structure and a band gap estimate.
    - By default, (1) can be the standard PBEsol pre-relax, but structuring it this way would allow the pre-relax step to be replaced with an alternative in future (for example an ML relaxer as in #322, perhaps). Having the PBEsol pre-relax as a default seems best for consistency with the MP workflow, but seems like a step that an advanced user may want to modify.

**Comment by mkhorton** [comment]
Added comments to #159 for the band gap question. Sorry for cross-posting, just want to make sure nothing gets lost and messages are linked appropriately.

**Comment by janosh** [comment]
@mkhorton I believe #362 fully implements both points in [your sketch](https://github.com/materialsproject/atomate2/issues/352#issuecomment-1559993418). Would be great to get your comments (if any) on that PR.
