### ISSUE TITLE
About zipping files at the end of a Job

### ISSUE THREAD

**Issue by gpetretto** [materialsproject/atomate2#361]
I have always had troubles with the fact that atomate (even v1) zips all the files in a folder. This typically ends up zipping the cluster queue files, preventing the writing from queue manager of additional informations (at least this is what happens in the clusters I have used). Other files can also end up zipped even if they are not supposed to.

I propose that 

1. the zipping can be disabled though an option in `Atomate2Settings` 
2. the preferred option would be not to zip the entire folder but just the files related to the executed code. Or maybe even just those that are expected to be large.

For VASP these lists can be used: https://www.vasp.at/wiki/index.php/Category:Output_files https://www.vasp.at/wiki/index.php/Category:Input_files. For Abinit I am still not sure if the zipping is easily manageable and we will need to see in future PR. I don't know if list of files are available for CP2K and Lobster.

If there is an interest in this I can open a PR.

**Comment by JaGeo** [comment]
@gpetretto I would be certainly interested to have this option for VASP as well. It makes debugging especially hard if all files are zipped (including error files). 

Within the Lobster workflow, I think we also zip everything at the moment: https://github.com/materialsproject/atomate2/blob/c2d098a38a41c181be2c483f8adb83db0223b76d/src/atomate2/lobster/jobs.py#L90

Within atomate, we actually did it differently and only zipped all files related to Lobster.

**Comment by JaGeo** [comment]
@gpetretto The typical output files for Lobster are available here: https://github.com/materialsproject/atomate2/blob/c2d098a38a41c181be2c483f8adb83db0223b76d/src/atomate2/lobster/files.py#L15

Input file is only "lobsterin" at the moment.

**Comment by arosen93** [comment]
A PR for this would likely look like the following:

Add a new variable to `settings.py`:

```python
 ZIP_FILES: bool = Field(True, description="Whether generated files should be zip'd.")
 ```
 
 Then in Atomate2, whenever a function zips files, it could take an optional kwarg of `zip_files: bool = SETTINGS.ZIP_FILES` with a `from atomate2 import SETTINGS` at the top.

**Comment by utf** [comment]
This was fixed in https://github.com/materialsproject/atomate2/pull/414

**Comment by 919607** [comment]
May I ask how to set the VASP file for compression? For example, if the WAVECAR is relatively large after calculation, I want to compress this file while not compressing the others
