### ISSUE TITLE
Connection of force-field models to phonon workflow

### ISSUE THREAD

**Issue by JaGeo** [materialsproject/atomate2#371]
@QuantumChemist and I plan to work on connection between the force field methods and a phonon workflow.

**Comment by matthewkuner** [comment]
@JaGeo @QuantumChemist  I plan on adding M3GNet support to the Atomate2 forcefields methods soon

**Comment by JaGeo** [comment]
@matthewkuner Thank you! I think we will try to generalize the phonon workflow in such a way that it should work with all future ML models/force fields. Hopefully, we can also support more quantum-chemical codes at some point.

**Comment by matthewkuner** [comment]
@JaGeo Cool cool. I do not currently plan on changing the `ForceFieldTaskDocument` anytime soon.

> Hopefully, we can also support more quantum-chemical codes at some point.
What do you mean by this? Like supporting Quantum Espresso or other DFT codes?

**Comment by JaGeo** [comment]
> What do you mean by this? Like supporting Quantum Espresso or other DFT codes?

Currently, the phonon workflow only works for VASP. I hope we can maybe connect it to Abinit (a pull request exists for static and relax runs, band structures etc) at some point as well! 😀 It's probably not a large change. If someone wants to write a QE interface, it's probably also easy to connect

**Comment by QuantumChemist** [comment]
@matthewkuner yeah, not changing the `ForceFieldTaskDocument` (much) is really appreciated 🙏
