### ISSUE TITLE
Adding M3GNet support to Atomate2 `forcefields` methods

### ISSUE THREAD

**Issue by matthewkuner** [materialsproject/atomate2#379]
FYI: I plan to add support for M3GNet to the Atomate2 `forcefields` methods soon

**Comment by arosen93** [comment]
FYI might want to consider using the model from `matgl`.

**Comment by matthewkuner** [comment]
> FYI might want to consider using the model from `matgl`.

Absolutely! I was waiting for the `matgl` model to be released before adding it (both so that we only need the `pytorch` dependency and because it is now the primary place for m3gnet development)

**Comment by matthewkuner** [comment]
Closed by #380
