### ISSUE TITLE
Should we update the Atomate2 docs with the version from `main`?

### ISSUE THREAD

**Issue by arosen93** [materialsproject/atomate2#383]
I didn't see the changes I made reflected in the public docs. Are you doing this after every release or after every docs update push?

**Comment by utf** [comment]
Docs get updated on each release but there is also a specific GitHub actions I can trigger.

Do you think they should be updated after each push?
________________________________
From: Andrew S. Rosen ***@***.***>
Sent: Saturday, June 10, 2023 6:47:09 PM
To: materialsproject/atomate2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [materialsproject/atomate2] BUG: Looks like the Atomate2 docs aren't getting updated? (Issue #383)


I didn't see the changes I made reflected in the public docs. Are you doing this after every release or after every docs update push?

**Comment by JaGeo** [comment]
I would vote for a more regular update.

**Comment by arosen93** [comment]
Also voting for a more regular update. For instance, the docs right now for how to use Fireworks with atomate2 aren't updated even though it'd be useful to have available.

Up to you though.

**Comment by mjwen** [comment]
How about using [readthedocs](https://readthedocs.org), which supports versioned docs? Then the default can be pointing to the released version; we can also have a latest version available in sync with main. 

It has a GitHub action and should be straightforward to setup.

**Comment by arosen93** [comment]
I don't think there's a need to switch the docs style. It's just a matter of building the docs in every push rather than on version releases (i.e. personal preference).

**Comment by janosh** [comment]
Also vote for updating docs on every `main` commit.

Having both the latest release docs and allowing people to opt into unreleased (as @mjwen suggested) is nice to have but auto-updating on every `main` commit is already an improvement imo. #422 does this.

**Comment by arosen93** [comment]
It's also consistent with what's done in the jobflow docs, I believe 😉
