### ISSUE TITLE
BUG: User Incar Settings being overridden by `auto_ismear` + others

### ISSUE THREAD

**Issue by matthewkuner** [materialsproject/atomate2#389]
https://github.com/materialsproject/atomate2/blob/51946bf1a5def3ab50fd4949111f96de37e976ff/src/atomate2/vasp/sets/base.py#L256

@utf the new `auto_ismear` argument (introduced in #270) appears to be overriding my UIS. 

Perhaps the `incar_updates` variable should be used instead of updating the `incar` directly in many places? I.e. I don't know why the `incar` is being updated directly on lines [661](https://github.com/materialsproject/atomate2/blob/51946bf1a5def3ab50fd4949111f96de37e976ff/src/atomate2/vasp/sets/base.py#L661), [664](https://github.com/materialsproject/atomate2/blob/51946bf1a5def3ab50fd4949111f96de37e976ff/src/atomate2/vasp/sets/base.py#L664), [668](https://github.com/materialsproject/atomate2/blob/51946bf1a5def3ab50fd4949111f96de37e976ff/src/atomate2/vasp/sets/base.py#L668), [674-678](https://github.com/materialsproject/atomate2/blob/51946bf1a5def3ab50fd4949111f96de37e976ff/src/atomate2/vasp/sets/base.py#L674), [681](https://github.com/materialsproject/atomate2/blob/51946bf1a5def3ab50fd4949111f96de37e976ff/src/atomate2/vasp/sets/base.py#L681), or [686 and 688](https://github.com/materialsproject/atomate2/blob/51946bf1a5def3ab50fd4949111f96de37e976ff/src/atomate2/vasp/sets/base.py#L686) -- this would overwrite the `user_incar_settings`. So either this should be changed, or the `user_incar_settings` should be applied last.

Separately, given that `auto_ispin` and `auto_lreal` are both false by default, I also feel like `auto_ismear` should be false by default.

I am confused

**Comment by matthewkuner** [comment]
After further investigation, I'm sure that the new `auto_ismear` block is the cause of this. See the attached file where I printed the `incar` after various steps in the `_get_incar` function.
[FW_job_error.txt](https://github.com/materialsproject/atomate2/files/11761208/FW_job_error.txt)

**Comment by utf** [comment]
Yes, this is a major bug. I think all those functions in `_get_incar` should be updating `incar_updates` rather than `incar`. There is a function call at the end of the function to apply the INCAR updates and avoid overwriting the user incar settings. E.g., 

https://github.com/materialsproject/atomate2/blob/51946bf1a5def3ab50fd4949111f96de37e976ff/src/atomate2/vasp/sets/base.py#L691

**Comment by matthewkuner** [comment]
@utf How about I just re-apply the UIS at the end of the incar generation? That should be fine as well, no?

**Comment by matthewkuner** [comment]
fixed in #412
