### ISSUE TITLE
Phonon workflow: improvement of band structure

### ISSUE THREAD

**Issue by JaGeo** [materialsproject/atomate2#409]
Potentially add `is_band_connection=True` to `run_bandstructure()`.
https://github.com/materialsproject/atomate2/blob/72b78c79427ee94b4954e8ff1fa5e07cecf803ce/src/atomate2/vasp/schemas/phonons.py#L308

(This is more a reminder to myself to fix and test this)

I could also add this and the computation of the the eigenvectors etc to the kwargs. This would however prevent getting the json for the phonon website.

**Comment by utf** [comment]
Has this been resolved now?

**Comment by JaGeo** [comment]
Yes.
