### ISSUE TITLE
Philosophical question: deciding between if something is a job vs. flow (e.g. for the `DoubleRelaxMaker`)?

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [materialsproject/atomate2#413]
Currently, the VASP `DoubleRelaxMaker` is a `Flow`, as shown [here](https://github.com/materialsproject/atomate2/blob/ce0a6f7dce23d9364d160ede4241f9738c3fafef/src/atomate2/vasp/flows/core.py#L44-L86). But in most cases, that second job is going to be extremely fast. So, one could argue that it would be better to define this as a single compute job. How do we, collectively, decide when to make such a decision?

This leads me to a related philosophical question of what do we define as flows vs. leaving it to the user? The `DoubleRelaxMaker` is a basic concatenation of two relax jobs, which the user could easily set up on their own via a custom `Flow` construction. I suppose it makes sense as a `Flow` because it's so widely used, but it would be good for us to establish some sort of soft criteria.

**Comment by JaGeo** [comment]
I would also tie it on how easily it can be combined to a flow and how often it will be used within other flows. I think as soon as we use a job combination in more than one flow, it should probably exist as a flow.

**Comment by arosen93** [comment]
Both points make sense to me! Once a consensus is reached, let's add it to the contributor docs.

**Comment by JaGeo** [comment]
But maybe, we should think about a good way to convert flows to single jobs?

**Comment by utf** [comment]
Regarding the double relax maker. It is possible to do this in a single job using the custodian double relax. E.g.,

```python
from atomate2.vasp.jobs.core import RelaxMaker
from atomate2.vasp.run import JobType

job = RelaxMaker(run_vasp_kwargs={"job_type": JobType. DOUBLE_RELAXATION}).make(structure)
```

This calls the `double_relax_run` in custodian: https://github.com/materialsproject/custodian/blob/26bf28a4b15b1253c955f3f8d6bd427bbc398e3a/custodian/vasp/jobs.py#L283

I'll note that this approach (the custodian double relax) was how it was done in atomate1. I decided to switch it to two separate calculations in atomate2 based on discussions with atomate users. Overall, the consensus was that it is nice to have one job refer to one DFT calculation for simplicity. Obviously this can result in a downgrade in performance if your workflow manager is configured to submit one compute job per jobflow job.
