### ISSUE TITLE
Mutable Pydantic-based kwargs can cause unexpected behavior

### ISSUE THREAD

**Issue by arosen93** [materialsproject/atomate2#428]
Throughout Atomate2, the Pydantic settings are defined in the kwargs as follows:

https://github.com/materialsproject/atomate2/blob/a6759f89d41c343f3e431b852ef140205169ce21/src/atomate2/vasp/run.py#L86-L97

However, because these settings are mutable, this goes against "best practices" and can lead to occasionally frustrating scenarios if (for instance) you define a new function in Atomate2 that tries to swap out a setting on-the-fly in the function definition. This is mostly me being a bit pedantic, but that is in the spirit of pydantic I guess 😅  The better solution would be to set them as `None` and if they're `None`, pull from the setting. Although you'll have to be careful because if the value can be `None`, then you don't want to use the default if the user specifies `None`.

**Comment by utf** [comment]
I'm not sure I follow @arosen93. It sounds like both your proposed implementation and the current implementation will have the same behaviour for the user?

**Comment by arosen93** [comment]
Yup, for the user the behavior remains entirely unchanged. This is a comment that would effect the developer experience only. That said, all of the settings right now are things a developer would never modify on-the-fly in a new Atomate2 function, so it probably doesn't matter (and you can close this if you'd like).

**Comment by arosen93** [comment]
Sure! Let's say that you have a global setting that is `CHECK_CONVERGENCE`, which by default is `True` and will make sure all Atomate2 calculations check for calculation convergence.

Now let's consider you're writing your test suite and you don't want `CHECK_CONVERGENE` to be `True` for some reason, e.g. because you're running some interatomic potential on some toy system but don't actually care if it runs all the way. The developer can't do

```python
from atomate2 import SETTINGS
SETTINGS.CHECK_CONVERGENCE = False
```
and expect the setting to pass down throughout the rest of the code being called.

Or, with this same example, if you knew a calculation should always be allowed to not be converged in the recipe, you can't do `SETTINGS.CHECK_CONVERGENCE = False` there either and expect it to carry over.

Now, this isn't really a relevant problem for any of the existing settings because there's no realistic scenario where a developer would change them. So, right now, it's more of a "don't set kwargs as mutable things in Python" suggestion.

Not sure if this helps clarify 😅

**Comment by utf** [comment]
That makes a lot of sense, thanks! It will add a bit more boilerplate code but I'm happy to accept this change. I can imagine someone running into this behaviour at some point.

**Comment by arosen93** [comment]
Yeah I ran into it in my own codes that copied your pydantic settings 😅 I mostly just wanted to bring it up here so you don't waste a few hours of your life if you run into the same thing.

I don't think it's necessarily worth adjusting now since it'll add boilerplate code but just a note for a future someone perhaps!
