### ISSUE TITLE
Including Forcefield methods

### ISSUE THREAD

**Issue by JaGeo** [materialsproject/atomate2#450]
Currently, the forcefields rely on the `TrajectoryObserver` from chgnet and megnet (it looks extremely similar in both codes). This, however, means that we would need to rely on it (or a similar class) for any kind of forcefield in the future. It also always includes magnetic moments by default (I don't think all force fields consider them; I ran into an issue with one ML potential). Any ideas how to solve this? Should we include our own TrajectoryObserver into atomate2? 

Currently, we also don't have any `ForcefieldBaseMaker` or similar.

I plan to write a RelaxMaker for EMT to test this in more detail. 

Any ideas, thoughts? @utf @matthewkuner @arosen93 @janosh ?

**Comment by arosen93** [comment]
Strictly speaking, `TrajectoryObserver` should only be needed if the force field method is implemented within ASE as a `Calculator`, right? So, presumably, if one made an Atomate2 recipe using (for example) GULP-based force fields, then there would be no need for a `TrajectoryObserver` for that code in practice.

**Comment by JaGeo** [comment]
@arosen93 thanks for the clarification with regard to the `TrajectoryObserver`.

**Comment by arosen93** [comment]
@JaGeo: Yes, I think that it is probably worth adding `TrajectoryObserver` to ASE as a class alongside `TrajectoryReader` and `TrajectoryWriter`. Someone with knowledge of ASE would have to open a PR for it of course. I'll probably get to it one day if nobody else does, but it's not high on my priority list...

**Comment by JaGeo** [comment]
@arosen93 Thanks! For now, I would probably need to include it into atomate2 to add further ase-based force fields and ML potentials.

We probably also need to add a `BaseForceFieldMaker` to simplify writing workflows for all forcefields...

**Comment by arosen93** [comment]
@JaGeo: Makes sense. In the meantime, I've opened an ASE issue here for the sake of bookkeeping: https://gitlab.com/ase/ase/-/issues/1293.

**Comment by arosen93** [comment]
@JaGeo: The lead dev of ASE responded to the above issue --- there isn't actually ever a need for `TrajectoryObserver` in practice. The same can be done just by passing a `trajectory` kwarg to the ASE `Optimizer` class (see [here](https://wiki.fysik.dtu.dk/ase/ase/optimize.html#bfgs)) and then adjusting the IO buffer size (as noted [here](https://gitlab.com/ase/ase/-/issues/1293)) so that it doesn't flush to disk every step. In the meantime, of course it might be easier to just copy the `TrajectoryObserver` to atomate2 directly, but longer term I think it's a class that doesn't really have to exist in the first place.

**Comment by matthewkuner** [comment]
@JaGeo Do you mean that the TrajectoryObserver always includes magmoms, or the ForceFieldTaskDocument? I'm unfamiliar with the larger pros/cons of storing this data in different forms and outsourced that opinion when I wrote the original forcefield code for Atomate2.

**Comment by JaGeo** [comment]
I think both. It caused an issues for me in case they were not defined. I will try to adapt both for this case.

**Comment by utf** [comment]
This has been resolved in #398
