### ISSUE TITLE
Migrate to 1st party GH Pages Deploy action

### ISSUE THREAD

**Issue by janosh** [materialsproject/atomate2#454]
GitHub added a [1st party Pages deploy action](https://github.com/actions/deploy-pages) a while back. See [e.g. here for usage example](https://github.com/janosh/workflows/blob/becb92eff4b140d78d094e45dc29684ef37861bf/.github/workflows/nodejs-gh-pages.yml).

We're currently using `peaceiris/actions-gh-pages`

https://github.com/materialsproject/atomate2/blob/59fd0b46b434d563b1621ee037fc8c4a55e6618e/.github/workflows/deploy.yml#L38-L42

but may want to consider migrating.

**Comment by utf** [comment]
This would be great to have!
