### ISSUE TITLE
BUG:Phonon workflow: Document size too large for MongoDB

### ISSUE THREAD

**Issue by JonathanSchmidt1** [materialsproject/atomate2#461]
When running a phonon workflow for a 20 atom cell with a 3x3x2 supercell, the last step ‘generate_frequencies_eigenvectors’ fizzled with the stackstrace posted below. The problem seems to be the mongodb limit of 16MB. However I thought this was circumvented by setting up the GridFSURIStore. I am not sure if this is a user error or sth is wrong with the code. Some of the workflow steps were restarted a few times, not sure if this is relevant. 
Thank you for you help
Ps: A  phonon workflow with a 5 atom structure and 3x3x3 supercell finished succesfully.

Stacktrace:
“_exception”: {
“_stacktrace”: “Traceback (most recent call last):\n File "/users/jschmidt/anaconda3/envs/fireworks/lib/python3.11/site-packages/maggma/stores/mongolike.py", line 494, in update\n self._collection.bulk_write(requests, ordered=False)\n File "/users/jschmidt/anaconda3/envs/fireworks/lib/python3.11/site-packages/pymongo/_csot.py", line 106, in csot_wrapper\n return func(self, *args, **kwargs)\n ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n File "/users/jschmidt/anaconda3/envs/fireworks/lib/python3.11/site-packages/pymongo/collection.py", line 548, in bulk_write\n bulk_api_result = blk.execute(write_concern, session)\n ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n File "/users/jschmidt/anaconda3/envs/fireworks/lib/python3.11/site-packages/pymongo/bulk.py", line 514, in execute\n return self.execute_command(generator, write_concern, session)\n ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n File "/users/jschmidt/anaconda3/envs/fireworks/lib/python3.11/site-packages/pymongo/bulk.py", line 391, in execute_command\n client._retry_with_session(self.is_retryable, retryable_bulk, s, self)\n File "/users/jschmidt/anaconda3/envs/fireworks/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1360, in _retry_with_session\n return self._retry_internal(retryable, func, session, bulk)\n ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n File "/users/jschmidt/anaconda3/envs/fireworks/lib/python3.11/site-packages/pymongo/_csot.py", line 106, in csot_wrapper\n return func(self, *args, **kwargs)\n ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n File "/users/jschmidt/anaconda3/envs/fireworks/lib/python3.11/site-packages/pymongo/mongo_client.py", line 1401, in _retry_internal\n return func(session, sock_info, retryable)\n ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n File "/users/jschmidt/anaconda3/envs/fireworks/lib/python3.11/site-packages/pymongo/bulk.py", line 385, in retryable_bulk\n self._execute_command(\n File "/users/jschmidt/anaconda3/envs/fireworks/lib/python3.11/site-packages/pymongo/bulk.py", line 338, in _execute_command\n result, to_send = bwc.execute(cmd, ops, client)\n ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n File "/users/jschmidt/anaconda3/envs/fireworks/lib/python3.11/site-packages/pymongo/message.py", line 841, in execute\n result = self.write_command(cmd, request_id, msg, to_send)\n ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n File "/users/jschmidt/anaconda3/envs/fireworks/lib/python3.11/site-packages/pymongo/helpers.py", line 279, in inner\n return func(*args, **kwargs)\n ^^^^^^^^^^^^^^^^^^^^^\n File "/users/jschmidt/anaconda3/envs/fireworks/lib/python3.11/site-packages/pymongo/message.py", line 920, in write_command\n reply = self.sock_info.write_command(request_id, msg, self.codec)\n ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n File "/users/jschmidt/anaconda3/envs/fireworks/lib/python3.11/site-packages/pymongo/pool.py", line 969, in write_command\n helpers._check_command_response(result, self.max_wire_version)\n File "/users/jschmidt/anaconda3/envs/fireworks/lib/python3.11/site-packages/pymongo/helpers.py", line 194, in _check_command_response\n raise OperationFailure(errmsg, code, response, max_wire_version)\npymongo.errors.**OperationFailure: BSONObj size: 17211573 (0x106A0B5) is invalid. Size must be between 0 and 16793600(16MB) First element: q: { uuid: "90370d8c-9822-46c5-ac5a-90f606bba2df", index: 1 }, full error: {‘ok’: 0.0, ‘errmsg’: ‘BSONObj size: 17211573 (0x106A0B5) is invalid. Size must be between 0 and 16793600(16MB) First element: q: { uuid: "90370d8c-9822-46c5-ac5a-90f606bba2df", index: 1 }’,** ‘code’: 10334, ‘codeName’: ‘BSONObjectTooLarge’, ‘$clusterTime’: {‘clusterTime’: Timestamp(1690548860, 30), ‘signature’: {‘hash’: b’\x1f\xd1u\xbe\x88]\xb4\xf5\xc6\xd9\xc7`\x19\xc4\xeb\xf1\xec\x16\x1d\xa5’, ‘keyId’: 7222757166363443201}}, ‘operationTime’: Timestamp(1690548860, 24)}\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n File "/users/jschmidt/anaconda3/envs/fireworks/lib/python3.11/site-packages/fireworks/core/rocket.py", line 261, in run\n m_action = t.run_task(my_spec)\n ^^^^^^^^^^^^^^^^^^^\n File "/users/jschmidt/anaconda3/envs/fireworks/lib/python3.11/site-packages/jobflow/managers/fireworks.py", line 160, in run_task\n response = job.run(store=store)\n ^^^^^^^^^^^^^^^^^^^^\n File "/users/jschmidt/anaconda3/envs/fireworks/lib/python3.11/site-packages/jobflow/core/job.py", line 607, in run\n store.update(data, key=["uuid", "index"], save=save)\n File "/users/jschmidt/anaconda3/envs/fireworks/lib/python3.11/site-packages/jobflow/core/store.py", line 328, in update\n self.docs_store.update(dict_docs, key=key)\n File "/users/jschmidt/anaconda3/envs/fireworks/lib/python3.11/site-packages/maggma/stores/mongolike.py", line 496, in update\n if self.safe_update:\n ^^^^^^^^^^^^^^^^\nAttributeError: ‘MongoURIStore’ object has no attribute ‘safe_update’\n”,
“_details”: null
}

Job store setup:
```
JOB_STORE:
docs_store:
type: MongoURIStore
uri: mongodb+srv://jschmidt2:pw@testfireworks.vlzxxmc.mongodb.net/fireworks?retryWrites=true&w=majority
collection_name: outputs
additional_stores:
data:
type: GridFSURIStore
uri: mongodb+srv://jschmidt2:pw@testfireworks.vlzxxmc.mongodb.net/fireworks?retryWrites=true&w=majority
collection_name: outputs_blobs
```
Code to create the workflow
```
rb_maker = PhononMaker()  
new_maker = update_user_incar_settings(rb_maker, {"GGA":'PS', "ENCUT":700, "NSIM":8})
phonon_flow = new_maker.make(structure, supercell_matrix=[[3.0,0.0,0.0],[0.0,3.0,0.0],[0.0,0.0,2.0]])

wf = flow_to_workflow(phonon_flow)

lpad = LaunchPad.auto_load()
lpad.add_wf(wf)
```

**Comment by JaGeo** [comment]
I had a similar error for the force constants and fixed it here: https://github.com/materialsproject/atomate2/pull/398.

Let me know if adding the force constants to the data store helps.

Just please be aware that we did not test the code in a high-throughput manner yet. Such issues might still occur.

**Comment by JaGeo** [comment]
@JonathanSchmidt1 Let me know if it works with the updated version of the code.

**Comment by JaGeo** [comment]
Short addition: you can also suppress saving the force constants to the db. This can be solved with a kwarg.
https://github.com/materialsproject/atomate2/blob/4fce631fe2cd85b6e936fe181d1d2374fdf0d4e7/src/atomate2/vasp/schemas/phonons.py#L442

**Comment by JonathanSchmidt1** [comment]
Thank you for your quick response.  Both suggestions worked with your branch.
And also thank you very much for the force field implementation. I just tried it with nequip yesterday and it worked great.

Maybe a follow up question to get the launchpad working with your branch and my existing database required me to copy quite a bit of code from the other branch because old modules were missing is there any different solution to this because I am afraid this will break as soon as I update.

**Comment by JaGeo** [comment]
`
> 
> Maybe a follow up question to get the launchpad working with your branch and my existing database required me to copy quite a bit of code from the other branch because old modules were missing is there any different solution to this because I am afraid this will break as soon as I update.

Oh, this shouldn't be happening. I moved some modules from the vasp part to the common part. Maybe, an issue with your local installation?
