### ISSUE TITLE
BUG: `_set_u_params` in `atomate2.vasp.sets.base.py`

### ISSUE THREAD

**Issue by esoteric-ephemera** [materialsproject/atomate2#465]
**Describe the bug**

When `LDAU*` tags are specified in `INCAR`, but all `+U` values are zero or unspecified, the current code (lines 940-943):

```python
if not has_u:
    for key in list(incar.keys()):
        if key.startswith("LDAU"):
            del incar[key]
```

throws a `RuntimeError: dictionary changed size during iteration`.

To fix this, it should be:

```python
if not has_u:
    redundant_ldau_keys = [key for key in incar if key.startswith("LDAU")]
    for key in redundant_ldau_keys:
        del incar[key]
```

**Comment by utf** [comment]
Thanks for catching this. Please can you submit a PR and add a test?
