### ISSUE TITLE
Deduplicate doc strings

### ISSUE THREAD

**Issue by janosh** [materialsproject/atomate2#488]
I've been meaning to bring this up for a while. @mkhorton's comment finally tipped me over the edge. 😄 

> @Janosh, separately, one thing I appreciate about the atomate2 code base is its terseness. Looking at a given file in atomate2, the ratio of docstring:code is often quite high, whereas it’s the reverse in pymatgen.

I fully agree with @mkhorton. `atomate2`'s design invites new workflows to inherit from base classes like

https://github.com/materialsproject/atomate2/blob/25f4c5dc185e243d0e73b8cca7103814780db016/src/atomate2/vasp/jobs/base.py#L85

and

https://github.com/materialsproject/atomate2/blob/25f4c5dc185e243d0e73b8cca7103814780db016/src/atomate2/vasp/sets/base.py#L209

which is great for getting up and running quickly and it also enforces consistency both in the API and in the underlying functionality.

That said, the doc strings in `atomate2` are an area that has a lot of low-hanging fruit when it comes to terseness and good coding practices such as DRYness. E.g. there are ~20 almost identical copies of the ~20 line `get_incar_updates()` doc string.

```py
    ) -> dict:
        """
        Get updates to the INCAR for a relaxation job.

        Parameters
        ----------
        structure
            A structure.
        prev_incar
            An incar from a previous calculation.
        bandgap
            The band gap.
        vasprun
            A vasprun from a previous calculation.
        outcar
            An outcar from a previous calculation.

        Returns
        -------
        dict
            A dictionary of updates to apply.
        """
```

That's 400 lines that could be consolidated down to ~40 by writing the doc string once as a template and then changing just the placeholders on a case by case basis. I would guess there are a dozen more chances for similar deduplication. 

I've contributed to `pandas` a few times and they have the best setup for doing exactly that I've come across. They have an `Appender` decorator that pulls doc strings from a `_shared_docs: dict[str, str] = {}` that can be defined per-module or even imported across modules.
[As an example](https://github.com/pandas-dev/pandas/blob/00f79a33f07d84192519165d29e028b26b874ec1/pandas/core/strings/accessor.py#L2876-L2883)

```py
    @Appender(
        _shared_docs["find"]
        % {
            "side": "lowest",
            "method": "find",
            "also": "rfind : Return highest indexes in each strings.",
        }
    )
    @forbid_nonstring_types(["bytes"])
    def find(self, sub, start: int = 0, end=None):
        ...
```

The best thing is, we know their setup works with `sphinx` docs since that's what they use.

**Comment by janosh** [comment]
Tagging @mattmcdermott since I remember we discussed the doc string duplication in `atomate2` and Matt mentioned he was considering submitting a PR for this.

**Comment by mattmcdermott** [comment]
@janosh this is a great suggestion! Much better than what I was proposing (which was literally changing the `__doc__` attribute.

**Comment by mkhorton** [comment]
I think maybe I was misconstrued, I actually like the docstrings. But no objection to deduplicating either :)

**Comment by JaGeo** [comment]
I just hope it's not making it even harder for new developers to get into. We should probably also mention this somewhere in the documentation

**Comment by JaGeo** [comment]
@utf I typically look into the code as well. Therefore, I am also happy about repetitions. I think we have to remember that the Python literacy that some of us have is not standard in the field. Some people might even still work without IDE.

Not directly related, but I recently talked to someone making the remark that the pymatgen documentation is rather short in general. I think this aligns with @mkhorton comment.

**Comment by janosh** [comment]
@JaGeo Without splitting hairs, I'd say short doc strings and duplicate doc strings are separate issues. I'm not advocating against longer doc strings if they add content.

> To me, codes like `pandas`, `plotly`, and `matplotlib` are a nightmare to understand what features are actually supported by a method.

@utf I think this criticism doesn't do their docs justice. Unlike `atomate2`, tools like `pandas`, `plotly`, and `matplotlib` have examples in most doc strings that help newcomers get going quickly. These examples show up inline on hover and while typing in any modern IDE. E.g. `pd.Series`

![Screenshot 2023-08-24 at 1 06 09 PM](https://github.com/materialsproject/atomate2/assets/30958850/58772c7d-4603-4183-97af-030e73dae253)

and `pd.Series` Examples:

![Screenshot 2023-08-24 at 1 06 22 PM](https://github.com/materialsproject/atomate2/assets/30958850/f86ad0f3-298d-4387-9ba3-cae648c9ff06)

For comparison, the `BandStructureMaker` on-hover docs:

![Screenshot 2023-08-24 at 1 06 33 PM](https://github.com/materialsproject/atomate2/assets/30958850/1abd735b-c50b-4849-8752-90998a34bb7e)

Speaking for myself, I often look at the tests in `atomate2` to see how something is used which serves a similar purpose as the Examples section in other docs. This is just to say that it's easy to criticize open-source projects developed and maintained with limited  resources if some of their shortcomings are also present in `atomate2` and likely for the same reasons.

Not to get too side-tracked on mostly unrelated issues though, the only thing I suggested is to deduplicate doc strings to ensure they remain consistent and complete. The only counterargument I heard to that is from @utf that it makes reading the docs directly in the code more difficult. That argument is valid but not as strong as having a single source of truth (my opinion) since the `_shared_docs` are always just a `cmd+click` away. Not sure about you guys but when I work on code, I already jump around a lot to the point that it's become muscle memory.

**Comment by janosh** [comment]
Forgot to say @mkhorton, I didn't mean to imply you don't like the current `atomate2` docs. Just that I agree with your assessment "in atomate2, the ratio of docstring:code is often quite high, whereas it’s the reverse in pymatgen." and that your comment reminded me that I wanted to open this issue for a while. 😄

**Comment by mkhorton** [comment]
Indeed, but my point was rather that pymatgen could be more like atomate2! 😁

**Comment by utf** [comment]
@janosh I would agree that having examples in the docstrings would be great. That's what we do in jobflow. But it takes a lot of time that I don't have. If others would be willing to add examples that would be wonderful.

In terms of pandas, matplotlib, and plotly, I wasn't saying that their documentation is bad, rather that it is hard to understand method signatures by looking at the code. Obviously, their built documentation is fantastic. But I think it is important to note that those projects are often relatively flat. If you look at their API docs, in most cases it is 2 levels deep: a handful of core classes, with many methods on them. This is ideal for a built documentation as a) you always know where you are and b) the sidebar doesn't get too cluttered. In atomate2 on the other hand, we have a very deep directory structure, which makes the built API docs rather unwieldy.

In terms of cmd+click or IDE hover. In my opinion, most users (not developers) of atomate2/pymatgen don't use an IDE. If they're looking at the code it will be on GitHub where you don't get the benefit of those features. Admitted GitHub has some form of lookup when you click a class name but it is not that smooth and regularly doesn't find the correct reference.

**Comment by janosh** [comment]
> The other argument is the one @JaGeo made.

I didn't experience this as a hurdle when contributing to `pandas`. Without me knowing the details of how `@Appender` works, the intent behind it was obvious and it's easy to copy so I don't think this is a strong argument.

Even if it was a hurdle, we can always let newcomers copy doc strings  and then maintainers deduplicate before merging a PR.

I also disagree with the flatness comparison. `pandas` and co. are much larger and at least as deep and unwieldy as `atomate2` which I think might be the main reason why you find them more difficult to learn.

I still believe the benefits of deduplicating doc strings outweigh the downsides. That said, @utf feel free to close this issue if you prefer the current setup.

**Comment by utf** [comment]
A tale of two side bars :)

<img width="281" alt="Screenshot 2023-08-24 at 22 43 23" src="https://github.com/materialsproject/atomate2/assets/1330638/cd8c9147-bed1-4372-9918-65f8f8186eeb">

<img width="346" alt="Screenshot 2023-08-24 at 22 41 34" src="https://github.com/materialsproject/atomate2/assets/1330638/9a599fbe-02a9-4047-a5ca-d6ac993c67e8">

Anyway, I will leave this open for now to hear any other opinions people have.

**Comment by arosen93** [comment]
Weighing in with my personal opinion to @utf's question: I almost always dive straight to the source code, particularly in a scientific software package where I have some idea of the context. De-duplicating the docstrings is a smart idea in principle, but I think in practice it will make it harder to see what's going on for the user.

There are already challenges associated with this in atomate2 as it is. For instance, if a user wants to find out what settings are used by the VASP `RelaxMaker`, they have to dive through several layers of inheritance just to find the settings. Adding additional layers of this kind of complexity may not be worth the tradeoff in my personal opinion.

**Comment by utf** [comment]
Ok, thank you all for the discussion. I will close this issue for now. If we find things get unmanageable in the future, then please feel free to re-open.
