### ISSUE TITLE
Problem with python 3.8 support with newer releases of dependencies

### ISSUE THREAD

**Issue by naik-aakash** [materialsproject/atomate2#530]
# Issue

`pymatgen` and `lobsterpy` no longer support python 3.8. This leads to failing tests with added new functionality., as atomate2 still supports python3.8

Can the python 3.8 support safely removed from atomate2 as well? Or is there any other work around to avoid this issue @utf ?

Thank you for your help :smile:  and looking forward to your thoughts on it

**Comment by JaGeo** [comment]
@naik-aakash Until this is resolved, just deactivate it in your branch and refine the tests.

@utf For context, We would like to integrate the Libster data into the MP database and would like to use the atomate2 schemata as a starting point for it.

**Comment by utf** [comment]
Atomate2 will follow pymatgen and remove support for python 3.8! Feel free at add this in a PR.

**Comment by naik-aakash** [comment]
> Atomate2 will follow pymatgen and remove support for python 3.8! Feel free at add this in a PR.

Thanks @utf . I Will raise a PR for it today
