### ISSUE TITLE
Incompatibility with pydantic-settings

### ISSUE THREAD

**Issue by zhenyaofang** [materialsproject/atomate2#535]
Hi,

While following the quick-start tutorial in the documentation, an error message shows up as "pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. 

This might be related to the 6th line in atomate2/settings.py: `from pydantic import BaseSettings, Field, root_validator`. So I modified it to `from pydantic.v1 import BaseSettings, Field, root_validator`. However, this produces another issue in pydantic that `_namespace` is not defined.

I also tried with downgrading pydantic to version 1.10.13, but this led to more incompatibility issues within atomate2. 

I was wondering if there are any solutions to this problem, and I appreciate any thoughts on this.

Thanks very much.

**Comment by katnykiel** [comment]
I am having the same issue, it appears to be due to a [recent version of pydantic](https://docs.pydantic.dev/2.4/migration/). I can still submit new workflows, but I can neither store these results or query past results.

**Comment by utf** [comment]
For now, you can install atomate2 using the strict dependencies and it should work fine. E.g.,
```bash
pip install atomate2[strict]
```
or if installing from source
```bash
pip install .[strict]
```

**Comment by zhenyaofang** [comment]
This works. Thanks very much for your help.
