### ISSUE TITLE
Remove `__all__` to discourage wildcard imports

### ISSUE THREAD

**Issue by janosh** [materialsproject/atomate2#539]
I think wildcard imports are a bad practice and a feature I wish Python didn't support.

By defining `__all__` across atomate2 modules, we're encouraging this practice. It's additional maintenance burden to keep the list of strings in sync with the actual symbol names in a module. It would also increase ecosystem consistency to remove them since other MP repos do not use `__all__`.

**Comment by chiang-yuan** [comment]
Fewer lines are always better 😎
