### ISSUE TITLE
`mock_vasp` should default to assert all INCAR tags match reference files

### ISSUE THREAD

**Issue by janosh** [materialsproject/atomate2#549]
The `mock_vasp` pytest fixture

https://github.com/materialsproject/atomate2/blob/468fb57b4a51a212ea385bed9e9ecae9b97dba4f/tests/vasp/conftest.py#L25-L33

by default doesn't check that the INCAR tags returned by the set generator being tested match the reference files. You have to explicitly pass per-job `incar_settings` to have them checked for agreement:

https://github.com/materialsproject/atomate2/blob/468fb57b4a51a212ea385bed9e9ecae9b97dba4f/tests/vasp/jobs/test_core.py#L148-L150

Maybe a better default behavior would be to check _all_ INCAR tags and allow passing `{"incar_settings": ["ISMEAR", "LREAL", "NSW"]}` if you only want to check that subset?

Pinging @esoteric-ephemera @JaGeo @Andrew-S-Rosen @mkhorton @computron to get a broad range of opinions.

**Comment by utf** [comment]
The issue with checking all input settings is that any time an input set changes you need to update all the test files which is a lot of work.

So the default has been to check only the settings that are important for that specific calculation (e.g., a relaxation should have NSW != 0.

**Comment by janosh** [comment]
Those cases you could still explicitly pass in a subset of tags to check. I feel like following the principle of least surprise here means checking all INCAR tags by default.

Maybe another option would be defining `__all__` as a special value for comparing the full generated INCAR to its reference. As it seems like a lot of boilerplate having to manually create a list of all INCAR tags that are present.

3rd option would be to define "ignore_incar_settings: list[str] | None = None" which when passed makes the test check all except the ignored INCAR tags.

**Comment by JaGeo** [comment]
I actually think it's a good idea to make sure more incar flags are tested. If @janosh did not realize all incar flags are tested by default, this will happen to many developers. To be honest, I had nearly overlooked this as well.

I would vote for option 1 proposed by @janosh, where one can check subsets of flags that need to pass.

**Comment by utf** [comment]
I'm not definitely not averse to imposing stricter checking. Especially if the input sets are settling down. But I just want to highlight that once the input sets are moved to pymatgen, if anyone makes an edit, this will cause a lot of atomate2 tests to fail. Whose responsibility is it to fix those failing tests? If we try and enforce that the person editing pymatgen also fixes atomate2, that will be fine. But otherwise, it will always come down to one of us fixing the tests and that can be a continued effort.

**Comment by janosh** [comment]
> But otherwise, it will always come down to one of us fixing the tests and that can be a continued effort.

That's a very good point. Maybe it's time to upstream the `mock_vasp` fixture to `pymatgen` and make sure the tests start failing there if someone changes an input set? Then they wouldn't need to be tested again in `atomate2`.

**Comment by janosh** [comment]
@utf Looks in #551 like defaulting to comparing full INCAR just breaks 1 test:

```
FAILED tests/vasp/flows/test_core.py::test_hse_optics - RuntimeError: Flow did not finish running successfully
============ 1 failed, 136 passed, 30 warnings in 432.53s (0:07:12) ============

INCAR value of ALGO is inconsistent: expected All, got Normal 
```
