### ISSUE TITLE
BUG: Schema overflow in Lobster workflow

### ISSUE THREAD

**Issue by JaGeo** [materialsproject/atomate2#572]
**Describe the bug**
When we run the Lobster workflow for larger structures (unit cells larger than 15 Angstroms in each direction), some of the schema (VASP and Lobster calculation), partially overflow and not all large objects are transferred to the datastore. 
We think that it is connected to the use of the `UniformBandStructureMaker` and the storing the band structures and DOS https://github.com/materialsproject/atomate2/blob/0dad7cbb23745295a8e09d98c3bdec798f8e3898/src/atomate2/vasp/flows/lobster.py#L29
To fix the VASP run, we reduced the kpoint density for a follow-up run. However, then the Lobster schema itself breaks. Here, we still need to investigate further which objects get so big that they need to be part of the datastore or if it is another error. We will try to address the second part within https://github.com/materialsproject/atomate2/pull/529 or a follow-up pull request.

In general, we might need to think about making a robustness test for our schemas in atomate2 (e.g., test larger structures), as this seems to be a common error showing up when the first larger tests are run.

**Comment by JaGeo** [comment]
@utf Could we move band structures and dos for all VASP schema's to the datastore? If I am not mistaken, this doesn't happen currently. (There is a lot of inheritance going on so that I had a hard time finding it). I think the Lobster error is a result of this. We can also switch the computation off for Lobster but it is likely that others will run into the same error just by using the UniformBandStructureMaker.

**Comment by JaGeo** [comment]
I think I have to check again more carefully! Thanks for pointing this out. Potentially, I was wrong.

**Comment by utf** [comment]
That is very worrying! Was this calculation dynamically created?

**Comment by JaGeo** [comment]
As a part of this flow: 
https://github.com/materialsproject/atomate2/blob/4e3d156d8c3b4fce475a00357d9022f1dbe0fec5/src/atomate2/vasp/flows/lobster.py#L57

**Comment by utf** [comment]
I wonder if the issue is related to this: https://github.com/materialsproject/jobflow/pull/409

I think the datastore information was not getting passed to dynamic flows before that.

**Comment by JaGeo** [comment]
I am updating the Maker for this run here: https://github.com/materialsproject/atomate2/blob/4e3d156d8c3b4fce475a00357d9022f1dbe0fec5/src/atomate2/vasp/jobs/lobster.py#L134

But I am surprised that only one of the outputs does not end up in the datastore and not both. This is very weird.

**Comment by JaGeo** [comment]
> I wonder if the issue is related to this: [materialsproject/jobflow#409](https://github.com/materialsproject/jobflow/pull/409)
> 
> I think the datastore information was not getting passed to dynamic flows before that.

Could be. I will try to rerun. Still puzzling that only the BandStructure gets left out.

**Comment by JaGeo** [comment]
It might be this change in jobflow. I just reran a Lobster workflow that I ran two months ago without any issue. Now, the document size is too large.

What do we do about it? I think it might not be desirable to just overwrite the kwargs as we do now in jobflow. Maybe, rather partially combine?

**Comment by JaGeo** [comment]
@utf I think the bug is not related to the workflow being dynamic. I just ran the tutorial example with fewer kpoints

```Python
from atomate2.vasp.flows.core import RelaxBandStructureMaker
from jobflow import run_locally
from pymatgen.core import Structure

# construct a rock salt MgO structure
mgo_structure = Structure(
    lattice=[[0, 2.13, 2.13], [2.13, 0, 2.13], [2.13, 2.13, 0]],
    species=["Mg", "O"],
    coords=[[0, 0, 0], [0.5, 0.5, 0.5]],
)

# make a band structure flow to optimise the structure and obtain the band structure
bandstructure_flow = RelaxBandStructureMaker().make(mgo_structure)

# run the job
run_locally(bandstructure_flow, create_folders=True)
```

And the band structure ends up in the MongoDB:
![image](https://github.com/materialsproject/atomate2/assets/22094846/cb513c8f-1155-4832-85c2-9cb413e23579)

But again, not the DOS:
![image](https://github.com/materialsproject/atomate2/assets/22094846/6d52c093-ac72-46f6-a331-d5053980f6d5)

I actually don't have any idea where this could come from but it's not a Lobster related issue.
