### ISSUE TITLE
BUG: BandStructure not in data store anymore

### ISSUE THREAD

**Issue by JaGeo** [materialsproject/atomate2#584]
@utf I think the bug described in #572  is not related to the workflow being dynamic. I just ran the tutorial example with fewer kpoints
```Python
from atomate2.vasp.flows.core import RelaxBandStructureMaker
from jobflow import run_locally
from pymatgen.core import Structure


mgo_structure = Structure(
    lattice=[[0, 2.13, 2.13], [2.13, 0, 2.13], [2.13, 2.13, 0]],
    species=["Mg", "O"],
    coords=[[0, 0, 0], [0.5, 0.5, 0.5]],
)

bandstructure_flow = RelaxBandStructureMaker().make(mgo_structure)

# run the job
run_locally(bandstructure_flow, create_folders=True)
```

And the band structure ends up in the MongoDB:
![image](https://github.com/materialsproject/atomate2/assets/22094846/cb513c8f-1155-4832-85c2-9cb413e23579)

But again, not the DOS:
![image](https://github.com/materialsproject/atomate2/assets/22094846/6d52c093-ac72-46f6-a331-d5053980f6d5)

I actually don't have any idea where this could come from but it's not a Lobster-workflow related issue alone.

**Comment by JaGeo** [comment]
Could someone else test this independently from me?

**Comment by utf** [comment]
This is so strange and I don't understand why this is happening. It should work to either specify an MSONable class OR a dictionary key. That said, I'm happy to merge the change in #605 while we investigate further.

**Comment by utf** [comment]
Ah, I figured it out! `BandStructure` is not MSONable for some reason.... https://github.com/materialsproject/pymatgen/blob/535f9252c15ea112969f2dba431442027a8a7e14/pymatgen/electronic_structure/bandstructure.py#L134

But `BandStructureSymmLine` is: https://github.com/materialsproject/pymatgen/blob/535f9252c15ea112969f2dba431442027a8a7e14/pymatgen/electronic_structure/bandstructure.py#L676

I think the proper fix is to make `BandStructure` MSONable but lets get this merged for now.
