### ISSUE TITLE
Minting new Atomate2 version that is pydantic2 compatible

### ISSUE THREAD

**Issue by matthewkuner** [materialsproject/atomate2#592]
@utf I think we should mint a new Atomate2 version so that users can simply `pip install atomate2 --upgrade` to get a version of atomate2 that is compatible with all the other MP codes' current versions (which all use pydantic2 now)

**Comment by JaGeo** [comment]
Yes, this would be in general very important. I think releases of new versions should be done more regularily and especially after a large implementation has taken place (i.e., a new workflow). Having to point people to the main branch of a repository (which might break or change frequently) is not a good practice when it comes to reproducibility.

**Comment by utf** [comment]
I just released a new version.
