### ISSUE TITLE
BUG: Pinning a version of numpy in requirements.txt

### ISSUE THREAD

**Issue by arosen93** [materialsproject/atomate2#62]
In a fresh Python 3.8 environment, I've run `pip install -r requirements.txt` and `pip install .[tests]` but get numpy issues in return. By default, I'm running numpy 1.21.5 with the above procedure. Upgrading to numpy 1.22.1 resolves it.

It might be good to pin a version to numpy in `requirements.txt` to resolve this (or might involve shuffling the order of some of the packages in `requirements.txt` so pymatgen is compatible with the numpy version).

```python
______________________ ERROR collecting test session _______________________ ..\..\miniconda3\envs\atomate2\lib\importlib\__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1014: in _gcd_import
    ???
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
<frozen importlib._bootstrap>:975: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:671: in _load_unlocked
    ???
..\..\miniconda3\envs\atomate2\lib\site-packages\_pytest\assertion\rewrite.py:170: in exec_module
    exec(co, module.__dict__)
tests\vasp\schemas\conftest.py:99: in <module>
    class SiNonSCFUniform(SchemaTestData):
tests\vasp\schemas\conftest.py:100: in SiNonSCFUniform
    from atomate2.vasp.schemas.calculation import VaspObject
..\..\miniconda3\envs\atomate2\lib\site-packages\atomate2\vasp\schemas\calculation.py:12: in <module>
    from pymatgen.command_line.bader_caller import bader_analysis_from_path
..\..\miniconda3\envs\atomate2\lib\site-packages\pymatgen\command_line\bader_caller.py:30: in <module>
    from pymatgen.io.cube import Cube
..\..\miniconda3\envs\atomate2\lib\site-packages\pymatgen\io\cube.py:46: in <module>
    from pymatgen.core.sites import Site
..\..\miniconda3\envs\atomate2\lib\site-packages\pymatgen\core\__init__.py:20: in <module>
    from .lattice import Lattice  # noqa
..\..\miniconda3\envs\atomate2\lib\site-packages\pymatgen\core\lattice.py:22: in <module>
    from pymatgen.util.coord import pbc_shortest_vectors
..\..\miniconda3\envs\atomate2\lib\site-packages\pymatgen\util\coord.py:17: in <module>
    from . import coord_cython as cuc
pymatgen/util/coord_cython.pyx:1: in init pymatgen.util.coord_cython
    ???
E   ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

**Comment by utf** [comment]
Ah, thanks for this. Pymatgen has numpy issues so I removed the numpy version from requirements.txt in the hope that pymatgen would do the pinning. But it seems like something isn't configured properly on pymatgens side...

I guess I can pin to the same version as pymatgen in requirements.txt and disable dependabot updates for numpy.

**Comment by arosen93** [comment]
I think if you remove the `numpy` dependency in `requirements.txt` and move `pymatgen` to the bottom, it should be okay. I just tried that and think that order worked.

**Comment by arosen93** [comment]
Actually, hold on for this. Looks like my `requirements.txt` may not have been what I thought it was. Will report back.

**Comment by arosen93** [comment]
Closed. I thought I pull'd the most recent updates to Atomate2 including the changes to `requirements.txt` but did not. I think your currently implementation does the right install.
