### ISSUE TITLE
how to stop PositiveEnergyErrorHandler

### ISSUE THREAD

**Issue by YuanbinLiu** [materialsproject/atomate2#639]
We need to do VASP calculations re high-energy structures whose energy is above 0. How to disable PositiveEnergyErrorHandler? Otherwise, the calculation cannot stop.

**Comment by JaGeo** [comment]
Hey @YuanbinLiu ,

You can use the kwargs for run vasp: https://github.com/materialsproject/atomate2/blob/bd434a695600a37188db73d23e156f3b90e326b0/src/atomate2/vasp/jobs/base.py#L168

Specificially, you have to pass a dict with these kwargs for custodian: 
https://github.com/materialsproject/atomate2/blob/bd434a695600a37188db73d23e156f3b90e326b0/src/atomate2/vasp/run.py#L92

**Comment by utf** [comment]
Customising the custodian error handlers is possible using the `run_vasp_kwargs` of the `BaseVaspMaker`. For example, to include all the default error handlers except `PositiveEnergyErrorHandler` you can do:


```python
from custodian.vasp.handlers import (
    FrozenJobErrorHandler,
    IncorrectSmearingHandler,
    LargeSigmaHandler,
    MeshSymmetryErrorHandler,
    NonConvergingErrorHandler,
    PotimErrorHandler,
    StdErrHandler,
    UnconvergedErrorHandler,
    VaspErrorHandler,
)

custom_handlers = (
    VaspErrorHandler(),
    MeshSymmetryErrorHandler(),
    UnconvergedErrorHandler(),
    NonConvergingErrorHandler(),
    PotimErrorHandler(),
    FrozenJobErrorHandler(),
    StdErrHandler(),
    LargeSigmaHandler(),
    IncorrectSmearingHandler(),
)

job = RelaxMaker(run_vasp_kwargs={"handlers": custom_handlers}).make(structure)
```

Alternatively, if you want to adjust the handlers for all VASP calculations in a flow, you can do:

```
from atomate2.vasp.jobs.base import BaseVaspMaker

flow = DoubleRelaxMaker().make(structure)
flow.update_maker_kwargs(
    {"_set": {"run_vasp_kwargs.handlers": custom_handlers}},
    dict_mod=True,
    class_filter=BaseVaspMaker
)

**Comment by JaGeo** [comment]
@utf thanks for the detailed answer. (maybe also something for the documentation as I assume this might be a frequently asked question in the future?)

**Comment by YuanbinLiu** [comment]
Thanks all, it works for me
