### ISSUE TITLE
BUG: error when supplying LDAUU/J/L through user_incar_settings

### ISSUE THREAD

**Issue by JonathanSchmidt1** [materialsproject/atomate2#646]
I am supplying custom user_incar_settings to a Relax workflow through update_user_incar_settings.
The LDA lines in the INCAR should look like:
> LDAU = True
LDAUJ = 1 0 0
LDAUL = 3 0 0
LDAUTYPE = 2
LDAUU = 5.75 0 0

but come out as :
> LDAU = True
LDAUJ = {'Eu': 1, 'Ti': 0, 'O': 0}
LDAUL = {'Eu': 3, 'Ti': 0, 'O': 0}
LDAUTYPE = 2
LDAUU = {'Eu': 5.75, 'Ti': 0, 'O': 0}

 resulting in a VASP warning and the LDAU/J/L values being ignored. 
 Running the relaxation example ends up with the same behavior:
 ```
from atomate2.vasp.jobs.core import RelaxMaker
from jobflow import run_locally
from pymatgen.core import Structure
print('starting')
# construct an FCC silicon structure
si_structure = Structure(
    lattice=[[0, 2.73, 2.73], [2.73, 0, 2.73], [2.73, 2.73, 0]],
    species=["Eu", "Eu"],
    coords=[[0, 0, 0], [0.25, 0.25, 0.25]],
)

# make a relax job to optimise the structure
relax_m = RelaxMaker()
incar_settings = {"LDAU":True, "LDAUU":{"Eu":5.75}, "LDAUJ":{"Eu":1},"LDAUL":{"Eu":3}}
from atomate2.vasp.powerups import update_user_incar_settings
relax_m_2 = update_user_incar_settings(relax_m, incar_settings)
relax_job = relax_m_2.make(si_structure)
print("starting")# run the job
run_locally(relax_job, create_folders=True)

```

I assume the problem appears due to the last:
```
        # Finally, re-apply `self.user_incar_settings` to make sure any accidentally
        # overwritten settings are changed back to the intended values.
        _apply_incar_updates(incar, self.user_incar_settings)
```
in vasp/sets/base.py

setting skip =["LDAU", ...] for this last update solves the issue for me. However I am not sure if this might have some unintended consequences that I am not aware of. I would also assume that the same problem will appear for every INCAR parameter that is supplied as such a dictionary.
This was tested with version 0.0.12.

**Comment by utf** [comment]
Hi @JonathanSchmidt1, thanks for this bug report. I think your suggested fix is correct, we need to add the correct skip statements to that function. Would you be able to submit a pull request with the fix?

**Comment by JonathanSchmidt1** [comment]
Sure I can submit a pull request.
 I checked and MAGMOM has the same issue:
> incar_settings = {"MAGMOM":{"Eu":10.}}
leads to:

> MAGMOM = {'Eu': 10.0}

 are you aware of any other dictionary parameters for the INCAR?

**Comment by utf** [comment]
The full list is: 'LDAUU', 'LDAUJ', 'LDAUL', 'MAGMOM'.

**Comment by JonathanSchmidt1** [comment]
I noticed that the line 648 in vasp/sets/base.py is      

>  magmoms=self.user_incar_settings.get("MAGMOMS", {})

while all other lines refer to MAGMOM without the final s. This leads to MAGMOM settings from the incar being ignored.
I will add another commit and pull request to fix it.

**Comment by JonathanSchmidt1** [comment]
Closed with https://github.com/materialsproject/atomate2/pull/648
