### ISSUE TITLE
BUG:Strict installation contains faulty github links

### ISSUE THREAD

**Issue by jmmshn** [materialsproject/atomate2#664]
https://github.com/materialsproject/atomate2/blob/554903c05fff763a41b2eb755c6de46e0e4ad8a3/pyproject.toml#L70-L80

It looks like there are a couple of github links under the [strict] installation.
They are breaking my local [strict] install on Python 3.9
Additionally, I think it's a good idea to make sure that merged PRs do not contain these kinds of deps.

**Comment by jmmshn** [comment]
After some quick digging it looks like ASE has not had a release since 2021, and `filters` stuff that is needed by M3GNET is newer.
So this looks like it can only be fixed on ASE's side.  (I think @askhl is a maintainer)

<img width="425" alt="image" src="https://github.com/materialsproject/atomate2/assets/14003693/7b952ea8-cda3-4a12-803b-d567483294aa">

**Comment by askhl** [comment]
It works, but I have problems due to a number of unrelated software disasters.

**Comment by utf** [comment]
Just to note that the `mace` github link has been removed in #668

**Comment by utf** [comment]
All GitHub/gitlab links have now been removed.
