### ISSUE TITLE
BUG: KeyError: 'efermi' in lobster example from documentation

### ISSUE THREAD

**Issue by JonathanSchmidt1** [materialsproject/atomate2#680]
**Describe the bug**
Running the plotting part from the lobster example in the documentation
```
for number, (key, cohp) in enumerate(
    result["output"]["lobsterpy_data"]["cohp_plot_data"].items()
):
    plotter = CohpPlotter()
    cohp = Cohp.from_dict(cohp)
    plotter.add_cohp(key, cohp)
    plotter.save_plot(f"plots_all_bonds{number}.pdf")
```
resulted in the error 
```
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "/home/sjonathan/anaconda3/envs/fireworks_mp/lib/python3.11/site-packages/pymatgen/electronic_structure/cohp.py", line 190, in from_dict
    dct["efermi"],
    ~~~^^^^^^^^^^
KeyError: 'efermi'
```
I assume  this is because:
```
result["output"]["lobsterpy_data"]["cohp_plot_data"].keys()
dict_keys(['data'])
```
adding ['data'] to the line to arrive at  result["output"]["lobsterpy_data"]["cohp_plot_data"]['data']
produces plots although I don't know whether the plots are correct.

**To Reproduce**
I ran the example through fireworks.
https://materialsproject.github.io/atomate2/user/codes/vasp.html#lobster
and then tried to run the given code to plot the results.

**Expected behavior**
Expected plots instead of error message.

**Comment by JaGeo** [comment]
@naik-aakash , could you check? I think this might be related to the schema updates. Thanks!

**Comment by JaGeo** [comment]
Thanks for reporting, @JonathanSchmidt1 .

**Comment by naik-aakash** [comment]
> @naik-aakash , could you check? I think this might be related to the schema updates. Thanks!

Yes, indeed due to added models in updates this error got introduced. Will fix the documentation. Got overlooked!
