### ISSUE TITLE
BUG: Atomate2 version number

### ISSUE THREAD

**Issue by arosen93** [materialsproject/atomate2#70]
The Atomate2 version property doesn't seem to work at the moment. This is also apparent when viewing the top of the [documentation](https://materialsproject.github.io/atomate2/) page where no version number is listed.

```python
import atomate2
atomate2.__version__
```

Returns `''`

**Comment by utf** [comment]
Thanks for flagging - fixed in c0ff6a471291aaff56342d480bebc1484a325414
