### ISSUE TITLE
[BUG] `ijson` is an optional import 

### ISSUE THREAD

**Issue by jmmshn** [materialsproject/atomate2#702]
I think `ijson` is an optional import for lobster but the lobster import is a part of the mp flow. 

https://github.com/materialsproject/atomate2/blob/8b1ee044674bb75ee9cd025d9ffc6d883f772fa5/src/atomate2/lobster/schemas.py#L10

https://github.com/materialsproject/atomate2/blob/8b1ee044674bb75ee9cd025d9ffc6d883f772fa5/src/atomate2/vasp/flows/mp.py#L18

This leads to import errors when lobster is not installed.

**Comment by JaGeo** [comment]
Tagging @naik-aakash : maybe enable the Lobster flow only if both LobsterPy and ijson exist in the environment.
