### ISSUE TITLE
Adding git tags

### ISSUE THREAD

**Issue by mjwen** [materialsproject/atomate2#711]
Currently, the repo is only tagged from 0.01 to 0.0.6. Because `verisoningit` is used to manage the versions, which uses git tag, if we do a local install like `pip install -e .`, the version would be something like `0.0.6+post2268...`. 

If one has a package that specifies e.g. `atomate2>=0.0.12` as a dependency and installs it, the already locally installed atomate2 will be replaced. This is not ideal if one is developing both codes. 

I think we should add tags to each release.

**Comment by utf** [comment]
> Currently, the repo is only tagged from 0.01 to 0.0.6. 

Where did you get that from? I see tags all the way to the most recent version: https://github.com/materialsproject/atomate2/tags

I use tags to trigger the automated release workflow, so I can't push a release without making a tag anyway.

**Comment by mjwen** [comment]
Thanks @utf ! 

I got the tags from my forked repo. 

I sync the forked repo with the upstream every so often. Just googled and found that simple sync will not get the tags from the upstream. I've manually synced the tags and everything works now.

**Comment by utf** [comment]
Ah phew! Glad there wasn't something more nefarious going on.
