### ISSUE TITLE
How to cite?

### ISSUE THREAD

**Issue by janosh** [materialsproject/atomate2#730]
I'd like to cite atomate2. can we add a `citation.cff` file similar to e.g. [`pymatgen`'s](https://github.com/materialsproject/pymatgen/blob/master/CITATION.cff) and a "How to cite" readme section? @utf @computron i can do this unless you guys have opinions on how it should be done?

**Comment by mkhorton** [comment]
A Zenodo citation would be nice too. I’m told by our EU colleagues that this can help on grant proposals etc.

**Comment by janosh** [comment]
@mkhorton good idea! doing Zenodo first also allows us to use https://github.com/citation-file-format/doi2cff to auto-generate the `citation.cff` file. a Zenodo entry for the last `atomate2` release is now at https://zenodo.org/records/10677081. i'll make a PR with a `citation.cff`
