### ISSUE TITLE
BUG: pip install atomate2 does not automatically install phonopy and seekpath

### ISSUE THREAD

**Issue by yaomz16** [materialsproject/atomate2#809]
**Describe the bug**
pip install atomate2 does not automatically install phonopy and seekpath. I have to manually install these 2 pkgs before running the tutorial at https://github.com/JaGeo/TutorialAtomate2Forcefields/blob/main/atomate2_workflow_tutorial/phonon.ipynb

Not a big deal but it takes some time to find it out, and it can be confusing for a green hand of automated pipeline

**Comment by JaGeo** [comment]
Hi @yaomz16 ,
Thanks for contacting us. Please check out the https://github.com/materialsproject/atomate2/blob/main/pyproject.toml 

You can install it with `pip install atomate2[phonons]`

There is also a strict installation: `pip install atomate2 [strict]`.

**Comment by JaGeo** [comment]
@utf maybe, we want to add this to the documentation?
