### ISSUE TITLE
Feature: Easy switch between GPU/CPU for forcefields

### ISSUE THREAD

**Issue by JaGeo** [materialsproject/atomate2#829]
For workstations, switching between GPUs and CPUs should be possible for the force field workflows. Do we currently have an easy option within the workflow to do so? 

We typically run these jobs on either GPUs or CPUs and rarely have an issue. Did anyone of you run into this? @esoteric-ephemera @janosh ? Especially in the context of CHGNet?

**Comment by janosh** [comment]
Are you asking about switching device mid-workflow? I've never tried or needed that, so can't comment.

To _initialize_ a workflow on different device, there's the [`use_device` kwarg](https://github.com/CederGroupHub/chgnet/blob/6408de5a2ae5760ad2f69c9272a3a26d37f83c01/chgnet/model/model.py#L675).

I was going to add a new parameter `model_kwargs` to the `ForceFieldMakers` be able to customize model loading including `use_device`

**Comment by JaGeo** [comment]
> Are you asking about switching device mid-workflow? I've never tried or needed that, so can't comment.
> 
> To _initialize_ a workflow on different device, there's the [`use_device` kwarg](https://github.com/CederGroupHub/chgnet/blob/6408de5a2ae5760ad2f69c9272a3a26d37f83c01/chgnet/model/model.py#L675).
> 
> I was going to add a new parameter `model_kwargs` to the `ForceFieldMakers` be able to customize model loading including `use_device`

I am asking about initialization

**Comment by esoteric-ephemera** [comment]
@janosh you can already pass that switch through `calculator_kwargs` if it's a kwarg of the ML model's calculator

**Comment by janosh** [comment]
sweet, i'd forgotten you added that in #722.

looks like there are some doc string vestiges from a MACE-specific version of that which I'd planned to standardize across models at some point. i'll remove those

https://github.com/materialsproject/atomate2/blob/348679239e21edbeb5b539c478401b3da1a68235/src/atomate2/forcefields/jobs.py#L406-L409

**Comment by JaGeo** [comment]
@esoteric-ephemera @janosh thank you both! I will then close this as resolved!
