### ISSUE TITLE
MLPs are not working in the test suite

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [materialsproject/atomate2#837]
**Describe the bug**

As described in further detail in https://github.com/materialsproject/atomate2/pull/834, both MACE-MP-0 and M3GNet tests are not running properly in CI.

**Comment by JaGeo** [comment]
Should be fixed now. I will close.

**Comment by Andrew-S-Rosen** [comment]
How was it fixed?

**Comment by JaGeo** [comment]
As a part of #723 , we updated the versions. As far as I see, all tests are passing again. And we did not skip anything

**Comment by JaGeo** [comment]
Closing again. Let me know if I am missing something
