### ISSUE TITLE
BUG: add_metadata_to_flow poweup does not work on PhononBSDOSDoc

### ISSUE THREAD

**Issue by naik-aakash** [materialsproject/atomate2#904]
# Summary

Ideally, the `atomate2.vasp.powerup.add_metadata_to_flow` should add the information supplied by the user as  "additional_fields" of the taskdoc. But as per the `PhononBSDOSDoc `schema, this field does not exists and powerup does not have indented effect

# Solution

Add the missing `additional_fields` field to the `PhononBSDOSDoc`. (Will be addressed in a PR shortly)

**Comment by JaGeo** [comment]
Thanks, @naik-aakash !
