### ISSUE TITLE
More frequent releases?

### ISSUE THREAD

**Issue by JaGeo** [materialsproject/atomate2#958]
When installing atomate2, we (my group) typically use an installation directly from the github repository at the moment. For using atomate2 in production and allowing for more reproducibility, this does not seem optimal to me. I personally think more frequent releases would help with this. 

I also just had a look at the statistics of the pypi and conda installations: 
[![PyPI Downloads](https://img.shields.io/pypi/dm/atomate2?logo=pypi&logoColor=white&color=blue&label=PyPI)](https://pypi.org/project/atomate2)
[![Conda Downloads](https://img.shields.io/conda/dn/conda-forge/atomate2?logo=condaforge&color=blue&label=Conda)](https://anaconda.org/conda-forge/atomate2)

They indicate that we are not the only ones mostly relying on the main branch of atomate2. I would have expected much higher numbers - I bet that I have already installed atomate2 a few hundred times myself but rarely via pypi or conda.

**Comment by utf** [comment]
Hi @JaGeo, thanks for raising this. I agree the releases should be more regular. Obviously it is difficult when something is always broken (e.g., at the moment, the tests are failing with the most recent pymatgen version) but 7 months between releases is too long.

I'll aim for a minimum of 1 release per month in the future. If more are needed in between then please let me know.

**Comment by JaGeo** [comment]
@utf yes, i agree that the broken tests are a huge problem... 

Thank you! I am also happy to help with releases if there is help needed.

**Comment by JaGeo** [comment]
@utf thank you! I will close this then. 1 release per month sounds great!

**Comment by JaGeo** [comment]
I would like to ask for a new release as I made some recent fixes in the QHAMaker.
