### ISSUE TITLE
Typo `mb_velocity_seed`

### ISSUE THREAD

**Issue by chiang-yuan** [materialsproject/atomate2#967]
Note to remember to fix this typo.

https://github.com/materialsproject/atomate2/blob/f14586c7b29a7d5cbf7eabfe399728ab6362e0e7/src/atomate2/forcefields/md.py#L145

**Comment by esoteric-ephemera** [comment]
Is this already fixed [here](https://github.com/materialsproject/atomate2/pull/940)?

**Comment by chiang-yuan** [comment]
Ahhh sorry that is an oversight. Close this now.
